### ISSUE TITLE
Not recording events in dashboard - Sentry Cloud  

### ISSUE THREAD

**Issue by amalpius** [getsentry/sentry-react-native#1093]
**OS:**
MacOS

**Platform:**
- iOS
- Android

**SDK:**
- [*]  `@sentry/react-native` (>= 1.0.0)

**SDK version:** 0.0.0

**`react-native` version:** "@sentry/react-native": "^1.8.0",

**Are you using Expo?**

- No

**Are you using sentry.io or on-premise?**
- sentry.io (SaaS)

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`react-native-sentry`)
```
Sentry.init({
      dsn: 'https://ingest.sentry.io/*****',
      debug: true,
      attachStacktrace: true,
      enableAutoSessionTracking: true,
      enabled: true,
      enableNative: true,
      enableNativeCrashHandling: true,
      logLevel: LogLevel.Verbose,
    });
```

---
**I have the following issue:**

throw new Error('My first Sentry error!'); is not getting reported in dashboard. 

Below are the logs 

Auto-init: false
Retrieving auto-init from AndroidManifest.xml
Sentry Logger [Log]: Integration installed: ReactNativeErrorHandlers
Sentry Logger [Log]: Integration installed: Release
Sentry Logger [Log]: Integration installed: InboundFilters
Sentry Logger [Log]: Integration installed: FunctionToString
Sentry Logger [Log]: Integration installed: Breadcrumbs
Sentry Logger [Log]: Integration installed: LinkedErrors
Sentry Logger [Log]: Integration installed: UserAgent
Sentry Logger [Log]: Integration installed: DebugSymbolicator
Sentry Logger [Log]: Integration installed: RewriteFrames
Sentry Logger [Log]: Integration installed: DeviceContext
sentry-debug-meta.properties file was not found.
Initializing SDK with DSN: 'https://io/******'
SU doesn't exist.
    java.io.IOException: Cannot run program "/system/xbin/which": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
        at java.lang.Runtime.exec(Runtime.java:698)
        at java.lang.Runtime.exec(Runtime.java:563)
        at io.sentry.android.core.util.RootChecker.checkSUExist(RootChecker.java:135)
        at io.sentry.android.core.util.RootChecker.isDeviceRooted(RootChecker.java:90)
        at io.sentry.android.core.DefaultAndroidEventProcessor.loadContextData(DefaultAndroidEventProcessor.java:114)
        at io.sentry.android.core.DefaultAndroidEventProcessor.lambda$new$0$DefaultAndroidEventProcessor(DefaultAndroidEventProcessor.java:102)
        at io.sentry.android.core.-$$Lambda$DefaultAndroidEventProcessor$ZsPdDrAaOs30gov_5eSNgy_KYe8.call(Unknown Source:2)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
        at java.lang.ProcessImpl.start(ProcessImpl.java:141)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        at java.lang.Runtime.exec(Runtime.java:698) 
        at java.lang.Runtime.exec(Runtime.java:563) 
        at io.sentry.android.core.util.RootChecker.checkSUExist(RootChecker.java:135) 
        at io.sentry.android.core.util.RootChecker.isDeviceRooted(RootChecker.java:90) 
        at io.sentry.android.core.DefaultAndroidEventProcessor.loadContextData(DefaultAndroidEventProcessor.java:114) 
        at io.sentry.android.core.DefaultAndroidEventProcessor.lambda$new$0$DefaultAndroidEventProcessor(DefaultAndroidEventProcessor.java:102) 
        at io.sentry.android.core.-$$Lambda$DefaultAndroidEventProcessor$ZsPdDrAaOs30gov_5eSNgy_KYe8.call(Unknown Source:2) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
GlobalHubMode: 'true'
UncaughtExceptionHandlerIntegration enabled: true
default UncaughtExceptionHandler class='com.facebook.internal.instrument.crashreport.CrashHandler'
UncaughtExceptionHandlerIntegration installed.
SendCachedEventFireAndForgetIntegration installed.
Started processing cached files from /data/user/0/com.abc.xyz/cache/sentry
Processing dir. /data/user/0/com.xyz.com/cache/sentry
SendCachedEventFireAndForgetIntegration installed.
NdkIntegration enabled: true
Processing 0 items from cache dir /data/user/0/com.xyz.com/cache/sentry
File /data/user/0/com.xyz.com/cache/sentry/outbox is not a File.
File /data/user/0/com.xyz.com/cache/sentry/sessions is not a File.
Finished processing cached files from /data/user/0/com.abc.xyz/cache/sentry
Started processing cached files from /data/user/0/com.abc.xyz/cache/sentry/sessions
Processing dir. /data/user/0/com.abc.xyz/cache/sentry/sessions
Processing 0 items from cache dir /data/user/0/com.abc.xyz/cache/sentry/sessions
Finished processing cached files from /data/user/0/com.abc.xyz/cache/sentry/sessions
NdkIntegration installed.
Registering EnvelopeFileObserverIntegration for path: /data/user/0/com.abc.xyz/cache/sentry/outbox
EnvelopeFileObserverIntegration installed.
SendCachedEventFireAndForgetIntegration installed.
AnrIntegration enabled: true
ANR timeout in milliseconds: 5000
Started processing cached files from /data/user/0/com.abc.xyz/cache/sentry/outbox
Processing dir. /data/user/0/com.abc.xyz/cache/sentry/outbox
Processing 0 items from cache dir /data/user/0/com.abc.xyz/cache/sentry/outbox
Finished processing cached files from /data/user/0/com.abc.xyz/cache/sentry/outbox
AnrIntegration installed.
enableSessionTracking enabled: true
enableAppLifecycleBreadcrumbs enabled: true
ActivityBreadcrumbsIntegration enabled: true
ActivityBreadcrumbsIntegration installed.
AppComponentsBreadcrumbsIntegration enabled: true
AppComponentsBreadcrumbsIntegration installed.
SystemEventsBreadcrumbsIntegration enabled: true
SystemEventsBreadcrumbsIntegration installed.
enableSystemEventsBreadcrumbs enabled: true
TYPE_AMBIENT_TEMPERATURE is not available.
enableSystemEventBreadcrumbs enabled: true
AppLifecycleIntegration installed.
Adding Envelope to offline storage: /data/user/0/com.abc.xyz/cache/sentry/sessions/6ad71e27-6f47-4d9a-8a1c-db2bbc5fbfb0.envelope
Envelope sent successfully.
Discarding envelope from cache: /data/user/0/com.abc.xyz/cache/sentry/sessions/6ad71e27-6f47-4d9a-8a1c-db2bbc5fbfb0.envelope
Envelope flushed

**Comment by jennmueng** [comment]
Hmm looking at your logs, it looks like the envelope should be sent correctly. Does the issue still persist now?

**Comment by amalpius** [comment]
Thanks @jennmueng . Yes, it is. The issue still persists.  Could there be an issue with the dashboard?

**Comment by jennmueng** [comment]
This is definitely unusual then, if your DSN is correct, and do other types of events not get reported as well? (such as `Sentry.captureMessage(...)`, `Sentry.captureException(...)`)

**Comment by ysfzrn** [comment]
Same issue happened to me. iOS app is working correctly but Android version's events is not listing in dashboard. I'm using captureMessage function.

**react-native version:** "react-native": "^0.62.2", "@sentry/react-native": "^1.8.2",

**Are you using Expo?**
No

**Are you using sentry.io or on-premise?**
sentry.io 

**If you are using sentry.io, please post a link to your issue so we can take a look:**
[Yeap, this is the problem already :) ]

**Configuration:**
(react-native-sentry)
```js
  Sentry.init({
        dsn:
          'https://***.ingest.sentry.io/****',
        logLevel: Sentry.Severity.Debug,
        debug: true,
        release: `${Device.getBundleId()}-${Device.getVersion()}`,
        dist: Device.getBuildNumber().toString(),
        environment: ENVIRONMENT,
      });
 ```

Initialize logs seem right
<img width="531" alt="Screen Shot 2020-11-17 at 23 20 45" src="https://user-images.githubusercontent.com/15312525/99443235-93817700-292b-11eb-8535-0badd5012cf2.png">

**Comment by jennmueng** [comment]
Looks like there have been no updates. Closing this for now. Let me know if the issue persists.
