### ISSUE TITLE
Errors are not captured from react-native app set up using yarn workspaces

### ISSUE THREAD

**Issue by varungupta85** [getsentry/sentry-react-native#1246]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 2.1.0

**`react-native` version:** 0.64.0-rc.1

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

Errors are not sent to Sentry

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
    dsn:
      'https://c123abc0:2123abc0@sentry.io/98211',
    release: release,
    dist: DeviceInfo.getBuildNumber()
  })
```

---
**I have following issue:**

I am currently using Sentry successfully in my mobile app. I am moving my app to a mono-repo managed using yarn workspaces. After moving to yarn-workspaces, the events are no longer reported. I see the following error in logcat

```
2020-12-16 04:58:01.361 19526-19647/com.galarmapp I/react-native-sentry: Starting with DSN: 'https://c123abc0:2123abc0@sentry.io/98211'
2020-12-16 04:58:01.361 19526-19647/com.galarmapp I/react-native-sentry: Native Integrations '[io.sentry.UncaughtExceptionHandlerIntegration@aba4f04, io.sentry.ShutdownHookIntegration@67f0ced, io.sentry.SendCachedEnvelopeFireAndForgetIntegration@656e722, io.sentry.android.core.NdkIntegration@3b8f5b3, io.sentry.android.core.EnvelopeFileObserverIntegration$OutboxEnvelopeFileObserverIntegration@c0f5770, io.sentry.SendCachedEnvelopeFireAndForgetIntegration@fcc8ae9, io.sentry.android.core.AnrIntegration@5a0536e, io.sentry.android.core.AppLifecycleIntegration@3c33a0f, io.sentry.android.core.ActivityBreadcrumbsIntegration@c6a7a9c, io.sentry.android.core.AppComponentsBreadcrumbsIntegration@b59eca5, io.sentry.android.core.SystemEventsBreadcrumbsIntegration@802387a, io.sentry.android.core.TempSensorBreadcrumbsIntegration@e83682b, io.sentry.android.core.PhoneStateBreadcrumbsIntegration@3f2a488]'
2020-12-16 04:58:01.363 19526-19665/com.galarmapp I/Sentry: sentry-debug-meta.properties file was not found.
2020-12-16 04:58:01.381 19526-19665/com.galarmapp D/Sentry: SU doesn't exist.
    java.io.IOException: Cannot run program "/system/xbin/which": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
        at java.lang.Runtime.exec(Runtime.java:699)
        at java.lang.Runtime.exec(Runtime.java:564)
        at io.sentry.android.core.util.RootChecker.checkSUExist(RootChecker.java:135)
        at io.sentry.android.core.util.RootChecker.isDeviceRooted(RootChecker.java:90)
        at io.sentry.android.core.DefaultAndroidEventProcessor.loadContextData(DefaultAndroidEventProcessor.java:114)
        at io.sentry.android.core.DefaultAndroidEventProcessor.lambda$new$0$DefaultAndroidEventProcessor(DefaultAndroidEventProcessor.java:102)
        at io.sentry.android.core.-$$Lambda$DefaultAndroidEventProcessor$NYQ5qA7CeWYLjnxHfVDRm7bpPQ0.call(Unknown Source:2)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
        at java.lang.ProcessImpl.start(ProcessImpl.java:141)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        at java.lang.Runtime.exec(Runtime.java:699) 
        at java.lang.Runtime.exec(Runtime.java:564) 
        at io.sentry.android.core.util.RootChecker.checkSUExist(RootChecker.java:135) 
        at io.sentry.android.core.util.RootChecker.isDeviceRooted(RootChecker.java:90) 
        at io.sentry.android.core.DefaultAndroidEventProcessor.loadContextData(DefaultAndroidEventProcessor.java:114) 
        at io.sentry.android.core.DefaultAndroidEventProcessor.lambda$new$0$DefaultAndroidEventProcessor(DefaultAndroidEventProcessor.java:102) 
        at io.sentry.android.core.-$$Lambda$DefaultAndroidEventProcessor$NYQ5qA7CeWYLjnxHfVDRm7bpPQ0.call(Unknown Source:2) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
```

**Steps to reproduce:**
- Create a react-native app as a package in yarn workspaces
- Setup Sentry and log a sample error

**Actual result:**

Error is not reported on Sentry.

**Expected result:**

Error should be reported on Sentry.

**Comment by draperunner** [comment]
We are also meeting these issues, using Yarn Workspaces and setting up `@sentry/react-native`. But I think I'm on the right track to finding a workaround. The issues are usually because of `node_modules` not being in the same directory as the react native project, but two directories higher in the tree (`../../node_modules`). 

The automatic gradle setup and linking did not work. We have issues with a bunch of libraries, so this is no surprise.

1. Add the library to your `android/settings.gradle`. Make sure to use the correct node_modules path (`../../../node_modules`)
```diff
+include ':@sentry_react-native'
+project(':@sentry_react-native').projectDir = new File(rootProject.projectDir, '../../../node_modules/@sentry/react-native/android')
```

2. Add the following to your `android/app/build.gradle`
```diff
+implementation project(':@sentry_react-native')
```

(Note: I didn't have to add SentryPackage to the `MainApplication.java` file.)

3. Apply the `sentry.gradle` file from the library in your `android/app/build.gradle`. Again, make sure to use the correct node_modules path
```diff
+apply from: "../../../../node_modules/@sentry/react-native/sentry.gradle"
```

4. Now we need to fix the path to the Sentry CLI executable that the `sentry.gradle` uses. You can configure this in your `android/sentry.properties` file and luckily relative paths work:
```diff
defaults.url=https://sentry.io/
defaults.org=myorg
defaults.project=myproject
auth.token=mysecrettoken
+cli.executable=../../node_modules/@sentry/cli/bin/sentry-cli
```

I hope this is helpful!

I'm still meeting some issues, but I don't think they're directly related to the use of Yarn Workspaces. Like, the wrong sourcemap path and filename is used, but I think that might be related to Hermes.

**Comment by marandaneto** [comment]
I think this issue is similar to https://github.com/getsentry/sentry-react-native/issues/1857
the stack trace in the description is just logging from the Android SDK and not really a problem, that logging is actually removed already from the most recent versions (months old already).

does this comment help solving the issue? https://github.com/getsentry/sentry-react-native/issues/1246#issuecomment-765511683
