### ISSUE TITLE
Sample app error /sample.app/main.jsbundle does not exist.

### ISSUE THREAD

**Issue by zazagag** [getsentry/sentry-react-native#1332]
### Environment

How do you use Sentry?
sentry.io

Which SDK and version?
@sentry/react-native:2.2.0

xcode: 12.4
MacOS Catalina: 10.15.4
node: 12.20.1

### Steps to Reproduce

1. Sample app run Archive

### Actual Result

```
error Unable to resolve module `../../dist/js` from `src/App.tsx`: 

None of these files exist:
  * ../dist/js(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * ../dist/js/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx). Run CLI with --verbose flag for more details.
Error: Unable to resolve module `../../dist/js` from `src/App.tsx`: 

None of these files exist:
  * ../dist/js(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * ../dist/js/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (/Users/xxx/code/native/sentry-react-native/sample/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (/Users/xxx/code/native/sentry-react-native/sample/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/xxx/code/native/sentry-react-native/sample/node_modules/metro/src/node-haste/DependencyGraph.js:287:16)
    at Object.resolve (/Users/xxx/code/native/sentry-react-native/sample/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /Users/xxx/code/native/sentry-react-native/sample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/xxx/code/native/sentry-react-native/sample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:431:18)
    at /Users/xxx/code/native/sentry-react-native/sample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/xxx/code/native/sentry-react-native/sample/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
+ [[ false != true ]]
+ [[ ! -f /Users/xxx/Library/Developer/Xcode/DerivedData/sample-cpoityqhtcyhgxdsqlzlkasuares/Build/Intermediates.noindex/ArchiveIntermediates/sample/BuildProductsPath/Release-iphoneos/sample.app/main.jsbundle ]]
+ echo 'error: File /Users/xxx/Library/Developer/Xcode/DerivedData/sample-cpoityqhtcyhgxdsqlzlkasuares/Build/Intermediates.noindex/ArchiveIntermediates/sample/BuildProductsPath/Release-iphoneos/sample.app/main.jsbundle does not exist. This must be a bug with'
error: File /Users/xxx/Library/Developer/Xcode/DerivedData/sample-cpoityqhtcyhgxdsqlzlkasuares/Build/Intermediates.noindex/ArchiveIntermediates/sample/BuildProductsPath/Release-iphoneos/sample.app/main.jsbundle does not exist. This must be a bug with
+ echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
React Native, please report it here: https://github.com/facebook/react-native/issues
```

**Comment by jennmueng** [comment]
Are you trying to build/archive the sample app on this repo? Make sure you run `yarn build` in the root folder before you try to build or run the sample app.

**Comment by zazagag** [comment]
Yes, I have installed all npm dependencies in both directories (`sample`, root) and Pods in `sample/ios` as well.
I am only changed `sentry.properties` (copied from own working project) and set `Signing...` for xcode and tap Product > Archive.
PS. Despite sample app not working for me, another project with @sentry/react-native:2.2.0 working well (I mean without any related issues).

xcode: 12.4
MacOS Catalina: 10.15.4
node: 12.20.1

**Comment by jennmueng** [comment]
Hmm, as long as you have built the SDK correctly and the `dist/js` directory exists, then this is certainly something regarding your setup as we haven't had any issues. I will be closing this for now.
