### ISSUE TITLE
Fail to Launch on Android after upgrading RN from 0.63.3 to 0.64.0

### ISSUE THREAD

**Issue by iyansr** [getsentry/sentry-react-native#1405]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 
Which SDK and version?
 "@sentry/react-native": "^2.3.0"
 React Native 0.64.0
 Windows 10
 Android 10.0

### Steps to Reproduce

1. yarn android

### Expected Result

Running Normally

### Actual Result

What actually happened. Maybe a screenshot/recording? Maybe some logs?

```
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1866 file(s) to forward-jetify. Using 12 workers...
info JS server already running.
info Installing the app...

> Configure project :app
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed in version 5.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.

> Configure project :react-native-firebase_analytics
:react-native-firebase_analytics package.json found at F:\DOOgether\Mobile\mobile-member\node_modules\@react-native-firebase\analytics\package.json
:react-native-firebase_app package.json found at F:\DOOgether\Mobile\mobile-member\node_modules\@react-native-firebase\app\package.json
:react-native-firebase_analytics:firebase.bom using default value: 24.1.0
:react-native-firebase_analytics package.json found at F:\DOOgether\Mobile\mobile-member\node_modules\@react-native-firebase\analytics\package.json
:react-native-firebase_analytics:version set from package.json: 7.0.1 (7,0,1 - 7000001)
:react-native-firebase_analytics:android.compileSdk using custom value: 29
:react-native-firebase_analytics:android.targetSdk using custom value: 29
:react-native-firebase_analytics:android.minSdk using custom value: 21
:react-native-firebase_analytics:reactNativeAndroidDir F:\DOOgether\Mobile\mobile-member\node_modules\react-native\android

> Configure project :react-native-firebase_app
:react-native-firebase_app package.json found at F:\DOOgether\Mobile\mobile-member\node_modules\@react-native-firebase\app\package.json
:react-native-firebase_app:firebase.bom using default value: 24.1.0
:react-native-firebase_app package.json found at F:\DOOgether\Mobile\mobile-member\node_modules\@react-native-firebase\app\package.json
:react-native-firebase_app:version set from package.json: 7.0.1 (7,0,1 - 7000001)
:react-native-firebase_app:android.compileSdk using custom value: 29
:react-native-firebase_app:android.targetSdk using custom value: 29
:react-native-firebase_app:android.minSdk using custom value: 21
:react-native-firebase_app:reactNativeAndroidDir F:\DOOgether\Mobile\mobile-member\node_modules\react-native\android

> Configure project :react-native-firebase_database
:react-native-firebase_database package.json found at F:\DOOgether\Mobile\mobile-member\node_modules\@react-native-firebase\database\package.json
:react-native-firebase_app package.json found at F:\DOOgether\Mobile\mobile-member\node_modules\@react-native-firebase\app\package.json
:react-native-firebase_database:firebase.bom using default value: 24.1.0
:react-native-firebase_database package.json found at F:\DOOgether\Mobile\mobile-member\node_modules\@react-native-firebase\database\package.json
:react-native-firebase_database:version set from package.json: 7.0.1 (7,0,1 - 7000001)
:react-native-firebase_database:android.compileSdk using custom value: 29
:react-native-firebase_database:android.targetSdk using custom value: 29
:react-native-firebase_database:android.minSdk using custom value: 21
:react-native-firebase_database:reactNativeAndroidDir F:\DOOgether\Mobile\mobile-member\node_modules\react-native\android
**********************************
* Flavor aware sentry properties *
**********************************

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* Where:
Script 'F:\DOOgether\Mobile\mobile-member\node_modules\@sentry\react-native\sentry.gradle' line: 129

* What went wrong:
Could not create task ':app:bundleReleaseJsAndAssets_SentryUpload_57'.
> Illegal null value provided in this collection: [/c, node, F:\DOOgether\Mobile\mobile-member\node_modules\@sentry\cli\bin\sentry-cli, --log-level, debug, --url, null, --auth-token, null, react-native, gradle, --bundle, F:\DOOgether\Mobile\mobile-member\android\app\build\generated\assets\react\release\index.android.bundle, --sourcemap, F:\DOOgether\Mobile\mobile-member\android\app\build\generated\sourcemaps\react\release\index.android.bundle.map, --release, com.doogether.android@3.7.2+57, --dist, 57, --org, null, --project, null]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Script 'F:\DOOgether\Mobile\mobile-member\node_modules\@sentry\react-native\sentry.gradle' line: 129

* What went wrong:
Could not create task ':app:bundleReleaseJsAndAssets_SentryUpload_57'.
> Illegal null value provided in this collection: [/c, node, F:\DOOgether\Mobile\mobile-member\node_modules\@sentry\cli\bin\sentry-cli, --log-level, debug, --url, null, --auth-token, null, react-native, gradle, --bundle, F:\DOOgether\Mobile\mobile-member\android\app\build\generated\assets\react\release\index.android.bundle, --sourcemap, F:\DOOgether\Mobile\mobile-member\android\app\build\generated\sourcemaps\react\release\index.android.bundle.map, --release, com.doogether.android@3.7.2+57, --dist, 57, --org, null, --project, null]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

    at makeError (F:\DOOgether\Mobile\mobile-member\node_modules\execa\index.js:174:9)
    at F:\DOOgether\Mobile\mobile-member\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

-------

Edit: 

Solved by modify `distributionUrl` on `android\gradle\wrapper\gradle-wrapper.properties` to :

`distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip`

**Comment by benoitvallon** [comment]
This is still happening to me even after trying your fix

**Comment by dsandmark** [comment]
Hade the same problem when upgrading from React Native 0.63.3 to 0.64.0.

The same solution worked for me, changing from using (as per https://react-native-community.github.io/upgrade-helper/?from=0.63.4&to=0.64.0):
> distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip

to
> distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip
