### ISSUE TITLE
Sentry.Init: 'Cannot read property 'bind' of undefined' when running jest

### ISSUE THREAD

**Issue by svenlombaert** [getsentry/sentry-react-native#1611]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
`"@sentry/react-native": "^2.5.0",`

### Steps to Reproduce

1. Run tests with jest

### Expected Result

Tests should run fine

### Actual Result

 Get this error:
```
  ● Test suite failed to run

    TypeError: Cannot read property 'bind' of undefined

      16 |     const appBuild = RNDeviceInfo.getBuildNumber();
      17 |
    > 18 |     Sentry.init({
         |            ^
      19 |       dsn:
      20 |         '...',
      21 |       ignoreErrors,

      at getNativeFetchImplementation (node_modules/@sentry/browser/src/transports/fetch.ts:73:20)
      at new FetchTransport (node_modules/@sentry/browser/src/transports/fetch.ts:84:72)
      at ReactNativeBackend._setupTransport (node_modules/@sentry/react-native/src/js/backend.ts:87:12)
      at ReactNativeBackend.BaseBackend (node_modules/@sentry/core/src/basebackend.ts:72:28)
      at new ReactNativeBackend (node_modules/@sentry/react-native/src/js/backend.ts:18:5)
      at ReactNativeClient.BaseClient (node_modules/@sentry/core/src/baseclient.ts:88:21)
      at new ReactNativeClient (node_modules/@sentry/react-native/src/js/client.ts:22:5)
      at initAndBind (node_modules/@sentry/core/src/sdk.ts:21:18)
      at Object.init (node_modules/@sentry/react-native/src/js/sdk.ts:82:3)
      at new ErrorHandler (src/client-blocks/helpers/ErrorHandler.ts:18:12)
```

This error started happening after I upgraded from 2.4.2 to 2.5.0. I setup sentry like this:
```
Sentry.init({
      dsn: '...',
      ignoreErrors,
      enableNative:
        typeof process?.env?.JEST_WORKER_ID !== 'undefined' ? false : true,
      release: `${bundleId}@${appVersion}+${appBuild}`,
    });
```

**Comment by jennmueng** [comment]
@svenlombaert When running jest tests, you would now have to pass `NoopTransport` to `Sentry.init` under `transport. You should be able to import it from `@sentry/react`.

**Comment by svenlombaert** [comment]
> @svenlombaert When running jest tests, you would now have to pass `NoopTransport` to `Sentry.init` under `transport`. You should be able to import it from `@sentry/react`. Although this will cause errors to not be sent (as the transport is a No-Op) I assume that should be fine unless you're also testing your Sentry integration?

This seems to work and is exactly what I need, thanks! Had to import `NoopTransport` from `@sentry/core` though. What's the default value of the transport param actually?

**Comment by jennmueng** [comment]
@svenlombaert So if `enableNative` is true, then it's `NativeTransport` by default, otherwise `FetchTransport`.

**Comment by jennmueng** [comment]
Closing this as it's been resolved, the docs issue will be tracked over at getsentry/sentry-docs#3740

**Comment by Rutvik17** [comment]
I am getting the following error and using `sentry-expo` when running a sample test and has nothing to do with sentry. Any suggestions ? Thank you.
```
TypeError: Cannot read properties of undefined (reading 'bind')

      at Object.utils_2 [as getNativeFetchImplementation] (node_modules/sentry-expo/node_modules/@sentry/react/node_modules/@sentry/src/transports/utils.ts:77:39)
      at new FetchTransport (node_modules/sentry-expo/node_modules/@sentry/react/node_modules/@sentry/src/transports/fetch.ts:14:72)
      at ReactNativeBackend._setupTransport (node_modules/sentry-expo/node_modules/@sentry/react-native/src/js/backend.ts:85:12)
      at new BaseBackend (node_modules/sentry-expo/node_modules/@sentry/src/basebackend.ts:79:28)
      at ReactNativeBackend._createSuperInternal (node_modules/sentry-expo/node_modules/@sentry/react-native/dist/js/backend.js:38:311)
      at new ReactNativeBackend (node_modules/sentry-expo/node_modules/@sentry/react-native/src/js/backend.ts:18:5)
      at new BaseClient (node_modules/sentry-expo/node_modules/@sentry/src/baseclient.ts:96:21)
      at ReactNativeClient._createSuperInternal (node_modules/sentry-expo/node_modules/@sentry/react-native/dist/js/client.js:26:311)
      at new ReactNativeClient (node_modules/sentry-expo/node_modules/@sentry/react-native/src/js/client.ts:21:49)
      at initAndBind (node_modules/sentry-expo/node_modules/@sentry/src/sdk.ts:32:18)
```

**Comment by Rutvik17** [comment]
> I am getting the following error and using `sentry-expo` when running a sample test and has nothing to do with sentry. Any suggestions ? Thank you.
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'bind')
> 
>       at Object.utils_2 [as getNativeFetchImplementation] (node_modules/sentry-expo/node_modules/@sentry/react/node_modules/@sentry/src/transports/utils.ts:77:39)
>       at new FetchTransport (node_modules/sentry-expo/node_modules/@sentry/react/node_modules/@sentry/src/transports/fetch.ts:14:72)
>       at ReactNativeBackend._setupTransport (node_modules/sentry-expo/node_modules/@sentry/react-native/src/js/backend.ts:85:12)
>       at new BaseBackend (node_modules/sentry-expo/node_modules/@sentry/src/basebackend.ts:79:28)
>       at ReactNativeBackend._createSuperInternal (node_modules/sentry-expo/node_modules/@sentry/react-native/dist/js/backend.js:38:311)
>       at new ReactNativeBackend (node_modules/sentry-expo/node_modules/@sentry/react-native/src/js/backend.ts:18:5)
>       at new BaseClient (node_modules/sentry-expo/node_modules/@sentry/src/baseclient.ts:96:21)
>       at ReactNativeClient._createSuperInternal (node_modules/sentry-expo/node_modules/@sentry/react-native/dist/js/client.js:26:311)
>       at new ReactNativeClient (node_modules/sentry-expo/node_modules/@sentry/react-native/src/js/client.ts:21:49)
>       at initAndBind (node_modules/sentry-expo/node_modules/@sentry/src/sdk.ts:32:18)
> ```

https://github.com/getsentry/sentry-react-native/issues/1611#issuecomment-862330959
This fixed it for me as well. Though would you please be able to explain what it does ? @svenlombaert @jennmueng

**Comment by JulianKingman** [comment]
Could someone the whole code snippet so I can see what it should look like? I'm having trouble importing NativeTransport without other issues. This is what I have so far:
```jsx
Sentry.init({
  environment: config.env, // 'production' | 'development' | 'staging'
  dsn:
    'https://example@example.ingest.sentry.io/example',
  integrations: [new Sentry.ReactNativeTracing({ routingInstrumentation })],
  enableNative:
    typeof process?.env?.JEST_WORKER_ID !== 'undefined' ? false : true,
  // dont upload stuff when jest tests
  transport:
    typeof process?.env?.JEST_WORKER_ID !== 'undefined'
      ? NoopTransport
      : NativeTransport,
});
```

**Comment by Rutvik17** [comment]
@JulianKingman 
```
import { NoopTransport } from '@sentry/core';

Sentry.init({
	dsn: Constants.manifest?.extra?.SENTRY_DSN,
	enableInExpoDevelopment: true,
	debug: true,
	transport: NoopTransport,
});
```

**Comment by gilisho** [comment]
@jennmueng can you explain why we have to pass `NoopTransport` under `transport` now? facing the same issue when migrating to Sentry v7 from v5.
