### ISSUE TITLE
Getting error while sentry integration

### ISSUE THREAD

**Issue by nikesh8** [getsentry/sentry-react-native#1613]
I am trying to installing the latest version of sentry and I am getting this error while executing following command:
**Command:**
**npx sentry-wizard -i reactNative -p ios android**

> "react-native: 0.64.2"
> "@sentry/react-native": "2.5.1"
> "@sentry/wizard": "1.2.7"

**Error:**
```
TypeError: Cannot read property 'match' of undefined
    at ReactNative._patchExistingXcodeBuildScripts (/Users/devtools/.npm/_npx/19242/lib/node_modules/@sentry/wizard/dist/lib/Steps/Integrations/ReactNative.js:258:37)
    at pbxProject.<anonymous> (/Users/devtools/.npm/_npx/19242/lib/node_modules/@sentry/wizard/dist/lib/Steps/Integrations/ReactNative.js:308:27)
    at pbxProject.emit (events.js:315:20)
    at pbxProject.<anonymous> (/Users/devtools/.npm/_npx/19242/lib/node_modules/@sentry/wizard/node_modules/xcode/lib/pbxProject.js:48:18)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
TypeError: Cannot read property 'match' of undefined
    at ReactNative._addNewXcodeBuildPhaseForSymbols (/Users/devtools/.npm/_npx/19242/lib/node_modules/@sentry/wizard/dist/lib/Steps/Integrations/ReactNative.js:276:36)
    at pbxProject.<anonymous> (/Users/devtools/.npm/_npx/19242/lib/node_modules/@sentry/wizard/dist/lib/Steps/Integrations/ReactNative.js:314:27)
    at pbxProject.emit (events.js:315:20)
    at pbxProject.<anonymous> (/Users/devtools/.npm/_npx/19242/lib/node_modules/@sentry/wizard/node_modules/xcode/lib/pbxProject.js:48:18)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

**Comment by jennmueng** [comment]
@nikesh8 You do have both iOS and Android project files correct? Not just Android?

**Comment by nikesh8** [comment]
> @nikesh8 You do have both iOS and Android project files correct? Not just Android?

Yes, I have both project's files correct. Still Can you please tell me what should I need to check?

**Comment by jennmueng** [comment]
@nikesh8 You will need to look into your Xcode build scripts and see if something is not in order, especially the one that is creating the React Native bundle. This error is most likely due to something being amiss there.

**Comment by nikesh8** [comment]
> @nikesh8 You will need to look into your Xcode build scripts and see if something is not in order, especially the one that is creating the React Native bundle. This error is most likely due to something being amiss there.

Okay, Let me check with it what's missing?

**Comment by nikesh8** [comment]
@jennmueng Thank you for helping and providing feedback. I am closing this as I understand what I missed!!
