### ISSUE TITLE
Fatal error on startup after upgrading to @sentry/react-native v3.0.1

### ISSUE THREAD

**Issue by prometheas** [getsentry/sentry-react-native#1757]
### Environment

How do you use Sentry?

Within a React Native app

Which SDK and version?

@sentry/react-native@3.0.1
Node v12.18.4
React Native 0.63.4
macOS 11.5.1 (20G80)
XCode Version 12.5.1 (12E507)

### Steps to Reproduce

Well, I can speak to my steps, which isn't exactly what this is asking, but it's the best I've got.

I had upgraded to v3.0.1, flushed out a bunch of caches, and fired up the app in the simulator by running the following sequence:

```sh
npm install @sentry/react-native@latest
cd ios
pod install --repo-update
pod update Sentry

# then clean everything out with a complete reinstall + caches clean
cd ..
rm -rf ios/Pods && rm -rf ios/build
rm -rf ./node_modules $TMPDIR/react-* $TMPDIR/npm-*
bash -c 'kill -9 $(lsof -t -i:8081) 2> /dev/null # kills metro packager
xcodebuild clean -project ios/MyApp.xcodeproj

# then run the app in simulator
react-native run-ios
```

### Expected Result

I expected the app's landing screen to render, and was going to poke around to validate that it seemed to be working properly.

### Actual Result

Instead, I was greeted with the following fatal error upon launch:

```
error: Error: Unable to resolve module ./lib/getFirstHidden from /PATH/TO/PROJECT_ROOT/node_modules/@sentry/tracing/dist/browser/web-vitals/getFID.js: 

None of these files exist:
  * node_modules/@sentry/tracing/dist/browser/web-vitals/lib/getFirstHidden(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.svg|.native.svg|.svg)
  * node_modules/@sentry/tracing/dist/browser/web-vitals/lib/getFirstHidden/index(.native|.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.svg|.native.svg|.svg)
> 1 | /*
  2 |  * Copyright 2020 Google LLC
  3 |  *
  4 |  * Licensed under the Apache License, Version 2.0 (the "License");
    at ModuleResolver.resolveDependency (/PATH/TO/PROJECT_ROOT/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:168:15)
    at DependencyGraph.resolveDependency (/PATH/TO/PROJECT_ROOT/node_modules/metro/src/node-haste/DependencyGraph.js:353:43)
    at Object.resolve (/PATH/TO/PROJECT_ROOT/node_modules/metro/src/lib/transformHelpers.js:271:42)
    at resolve (/PATH/TO/PROJECT_ROOT/node_modules/metro/src/DeltaBundler/traverseDependencies.js:571:33)
    at /PATH/TO/PROJECT_ROOT/node_modules/metro/src/DeltaBundler/traverseDependencies.js:587:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/PATH/TO/PROJECT_ROOT/node_modules/metro/src/DeltaBundler/traverseDependencies.js:586:33)
    at /PATH/TO/PROJECT_ROOT/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/PATH/TO/PROJECT_ROOT/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
```

**Comment by jennmueng** [comment]
@prometheas Do you have `@sentry/tracing` as a dependency in your `package.json`? You will need to remove it as this SDK has its own dependency and will almost always require a specific version.

**Comment by jennmueng** [comment]
Closing this due to no response, along with us most likely knowing what caused it.
