### ISSUE TITLE
[Android] ConcurrentModification exception for frameMetricsAggregator

### ISSUE THREAD

**Issue by jayshah-swiggy** [getsentry/sentry-react-native#1865]
### Environment

How do you use Sentry?
sentry.io

Which SDK and version?
Sentry react native. 3.0.0

### Steps to Reproduce

Some of the app launches show following stack trace:
```
java.util.ConcurrentModificationException: null
    at java.util.ArrayList$Itr.next(ArrayList.java:860)
    at android.view.View.registerPendingFrameMetricsObservers(View.java:6363)
    at android.view.View.dispatchAttachedToWindow(View.java:17755)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3417)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1932)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1647)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7595)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:988)
    at android.view.Choreographer.doCallbacks(Choreographer.java:800)
    at android.view.Choreographer.doFrame(Choreographer.java:713)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:974)
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:6977)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:528)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:910)

```

### Expected Result

No error

Here is my reasoning:
`RNSentryModule` is the only package registering `frameMetricsAggregator`.
 
I think the temp fix would be to disable perf tracking via turning off `enableAutoPerformanceTracking`, 
but this seems like something worth looking into.

### Actual Result

```
java.util.ConcurrentModificationException: null
    at java.util.ArrayList$Itr.next(ArrayList.java:860)
    at android.view.View.registerPendingFrameMetricsObservers(View.java:6363)
    at android.view.View.dispatchAttachedToWindow(View.java:17755)
    at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3417)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1932)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1647)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7595)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:988)
    at android.view.Choreographer.doCallbacks(Choreographer.java:800)
    at android.view.Choreographer.doFrame(Choreographer.java:713)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:974)
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:6977)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:528)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:910)
```

**Comment by jayshah-swiggy** [comment]
@marandaneto 
Sentry is adding framemetrics listener via https://github.com/getsentry/sentry-react-native/blob/master/android/src/main/java/io/sentry/react/RNSentryModule.java#L136

Which uses following api internally:
https://developer.android.com/reference/android/view/Window?hl=en#addOnFrameMetricsAvailableListener(android.view.Window.OnFrameMetricsAvailableListener,%20android.os.Handler)

My assumption is this should probably be posted to main activity thread, currently it seems to be happening from native_modules thread.

**Comment by marandaneto** [comment]
@jayshah-swiggy thanks for replying, removing Sentry does the crash stop? I can't reproduce it using the latest versions, have you tried upgrading the Sentry RN SDK?

Please, set up a minimal reproducible example on GH, thanks

**Comment by jayshah-swiggy** [comment]
We will do a release with auto perf tracking and see if issue subsides. will let you know.

**Comment by marandaneto** [comment]
@jayshah-swiggy while disabling auto perf tracking is a workaround for you, we'd really appreciate a minimal reproducible example, so we could debug and solve it if it's a Sentry issue, thanks.

**Comment by marandaneto** [comment]
thanks @jayshah-swiggy we will have a look
