### ISSUE TITLE
Application Crash on Launch in Samsung Device 

### ISSUE THREAD

**Issue by mahipalsingh-syt** [getsentry/sentry-react-native#2215]
Application Crash on Launch in Samsung Device  and if i run application without Sentry then it working fine.

Samsung Device :
Android OS: 8
Model: Samsung Galaxy S7

React Native: 0.68
"@sentry/react-native": "^3.4.1",
 "react-native": "0.68.0",

 Gradle:
 ext {
        buildToolsVersion = "30.0.2"
        minSdkVersion = 23
        compileSdkVersion = 31
        targetSdkVersion = 31
        multiDexEnabled = true
    }
 
 
 Log: 
 
 ``
 2022-04-24 11:42:49.962 3391-3391/com.stage E/SoLoader: couldn't find DSO to load: libjscexecutor.so
    	SoSource 0: com.facebook.soloader.a[root = /data/data/com.stage /lib-main flags = 1]
    	SoSource 1: com.facebook.soloader.c[root = /data/app/com.stage -ugzesClIF9HORgY5bgssxA==/lib/x86 flags = 0]
    	SoSource 2: com.facebook.soloader.c[root = /system/vendor/lib flags = 2]
    	SoSource 3: com.facebook.soloader.c[root = /system/lib flags = 2]
    	Native lib dir: /data/app/com.stage -ugzesClIF9HORgY5bgssxA==/lib/x86
     result: 0
2022-04-24 11:42:50.005 3391-3391/com.stage  E/SoLoader: couldn't find DSO to load: libhermes-executor-debug.so
    	SoSource 0: com.facebook.soloader.a[root = /data/data/com.stage /lib-main flags = 1]
    	SoSource 1: com.facebook.soloader.c[root = /data/app/com.stage -ugzesClIF9HORgY5bgssxA==/lib/x86 flags = 0]
    	SoSource 2: com.facebook.soloader.c[root = /system/vendor/lib flags = 2]
    	SoSource 3: com.facebook.soloader.c[root = /system/lib flags = 2]
    	Native lib dir: /data/app/com.stage -ugzesClIF9HORgY5bgssxA==/lib/x86
     result: 0
2022-04-24 11:42:50.206 3391-3419/com.stage  E/eglCodecCommon: goldfish_dma_create_region: could not obtain fd to device! fd -1 errno=2
2022-04-24 11:42:53.646 3391-3428/com.stage  E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.stage , PID: 3391
    java.lang.RuntimeException: Could not invoke RNSentry.initNativeSdk
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:22)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:13)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:18)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:13) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1) 
        at android.os.Looper.loop(Looper.java:164) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.lang.IncompatibleClassChangeError: The method 'java.lang.String java.lang.Object.toString()' was expected to be of type interface but instead was found to be of type virtual (declaration of 'io.sentry.react.RNSentryModule' appears in /data/app/com.stage -ugzesClIF9HORgY5bgssxA==/base.apk)
        at io.sentry.react.RNSentryModule.lambda$initNativeSdk$1(RNSentryModule.java:49)
        at io.sentry.react.RNSentryModule.b(Unknown Source:0)
        at a9.g.configure(Unknown Source:6)
        at io.sentry.android.core.SentryAndroid.lambda$init$1(SentryAndroid.java:5)
        at io.sentry.android.core.SentryAndroid.b(Unknown Source:0)
        at io.sentry.android.core.l.configure(Unknown Source:8)
        at io.sentry.Sentry.init(Sentry.java:5)
        at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:7)
        at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:3)
        at io.sentry.react.RNSentryModule.initNativeSdk(RNSentryModule.java:1)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:18) 
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:13) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1) 
        at android.os.Looper.loop(Looper.java:164) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8) 
        at java.lang.Thread.run(Thread.java:764) 
2022-04-24 11:42:54.405 3391-3419/com.stage  E/eglCodecCommon: goldfish_dma_create_region: could not obtain fd to device! fd -1 errno=2
2022-04-24 11:42:54.595 3391-3391/com.stage E/unknown:ReactNative: Tried to remove non-existent frame callback
2022-04-24 11:42:54.603 3391-3391/com.stage  E/WindowManager: android.view.WindowLeaked: Activity com.stage.MainActivity has leaked window DecorView@a4e5d35[] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:485)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:92)
        at android.app.Dialog.show(Dialog.java:330)
        at qa.c$a.run(SplashScreen.java:8)
        at android.app.Activity.runOnUiThread(Activity.java:6152)
        at qa.c.g(SplashScreen.java:2)
        at qa.c.h(SplashScreen.java:2)
        at qa.c.f(SplashScreen.java:1)
        at com.stage.MainActivity.onCreate(MainActivity.java:1)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
 
 ``

**Comment by marandaneto** [comment]
@mahipalsingh-syt have you tried the rebuild the App and try again? it crashed while initing the Sentry SDK but seems more like a broken build.
I can't reproduce that locally but I don't have this device specifically, mind providing a minimal reproduction example? thanks

**Comment by mahipalsingh-syt** [comment]
@marandaneto Yes i tried with all settings (Cleaning cache and rebuilding) but still same issue i facing 

today i tried with Samsung A10 Android 9.0 (Api 28), it working But not working with Model: Samsung Galaxy S7 Android 8.0 (Api 26)

i created all these Samsung device with GenyMotion software.

**Comment by marandaneto** [comment]
@mahipalsingh-syt I just have tested with GenyMotion and both emulators (A10 API 28 and S7 API 26) and everything worked out, it should be something else in your environment?

Please provide a minimal reproduction example, thanks.

**Comment by mahipalsingh-syt** [comment]
@marandaneto  i have create a fresh project using  `npx react-native init AwesomeProject` and then i install sentry in that but still same issue with 

Android OS: 8.0.0 (Api 26)
Model: Samsung Galaxy S7


Here i have setup details :

"dependencies": {
    "@sentry/react-native": "^3.4.1",
    "react": "17.0.2",
    "react-native": "0.68.1",
    "react-native-device-info": "^8.7.0"
  },
  
  
  npm: '8.7.0',
  node: '17.3.1',

Java Version:
openjdk version "18" 2022-03-22
OpenJDK Runtime Environment Temurin-18+36 (build 18+36)
OpenJDK 64-Bit Server VM Temurin-18+36 (build 18+36, mixed mode, sharing)



`

**Comment by marandaneto** [comment]
@mahipalsingh-syt afaik you can't use Java 18 to build an Android project yet, but only Java 8 or 11, can you try with one of these 2?

**Comment by mahipalsingh-syt** [comment]
@marandaneto  working with JAVA_SDK_11 but i'm wondering all the versions(>27) are working perfectly with JDK_18. So why lower versions are not working?

**Comment by marandaneto** [comment]
> @marandaneto working with JAVA_SDK_11 but i'm wondering all the versions(>27) are working perfectly with JDK_18. So why lower versions are not working?

The Android OS supports only Java 8 or 11 for now, so I can't do much about it.
