### ISSUE TITLE
Flaky e2e CI

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry-react-native#2474]
### Description

cmd: `react-native run-ios --configuration Release --simulator "${DEVICE}"`

https://github.com/getsentry/sentry-react-native/actions/runs/3058663164/jobs/4935127518

```
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - @sentry/react-native (to unlink run: "react-native unlink @sentry/react-native")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
info Found Xcode workspace "sample.xcworkspace"
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10827 "kLSNoExecutableErr: The executable is missing" UserInfo={_LSLine=3878, _LSFunction=_LSOpenStuffCallLocal}
error Command failed: open /Applications/Xcode_13.2.1.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID 3[11](https://github.com/getsentry/sentry-react-native/actions/runs/3058663164/jobs/4935127518#step:15:12)A4EFB-6F90-4877-A924-B5C233CE41B3
Error: Command failed: open /Applications/Xcode_13.2.1.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID 311A4EFB-6F90-4877-A924-B5C233CE41B3
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10827 "kLSNoExecutableErr: The executable is missing" UserInfo={_LSLine=3878, _LSFunction=_LSOpenStuffCallLocal}
The application cannot be opened for an unexpected reason, error=Error Domain=NSOSStatusErrorDomain Code=-10827 "kLSNoExecutableErr: The executable is missing" UserInfo={_LSLine=3878, _LSFunction=_LSOpenStuffCallLocal}
.

    at checkExecSyncError (child_process.js:635:11)
    at Object.execFileSync (child_process.js:653:15)
    at runOnSimulator (/Users/runner/work/sentry-react-native/sentry-react-native/sample/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js:208:28)
    at Object.runIOS [as func] (/Users/runner/work/sentry-react-native/sentry-react-native/sample/node_modules/@react-native-community/cli-platform-ios/build/commands/runIOS/index.js:[12](https://github.com/getsentry/sentry-react-native/actions/runs/3058663164/jobs/4935127518#step:15:13)1:12)
    at Command.handleAction (/Users/runner/work/sentry-react-native/sentry-react-native/sample/node_modules/@react-native-community/cli/build/index.js:192:23)
    at Command.listener (/Users/runner/work/sentry-react-native/sentry-react-native/sample/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:3[14](https://github.com/getsentry/sentry-react-native/actions/runs/3058663164/jobs/4935127518#step:15:15):[20](https://github.com/getsentry/sentry-react-native/actions/runs/3058663164/jobs/4935127518#step:15:21))
    at Command.parseArgs (/Users/runner/work/sentry-react-native/sentry-react-native/sample/node_modules/commander/index.js:651:12)
    at Command.parse (/Users/runner/work/sentry-react-native/sentry-react-native/sample/node_modules/commander/index.js:474:21)
    at setupAndRun (/Users/runner/work/sentry-react-native/sentry-react-native/sample/node_modules/@react-native-community/cli/build/index.js:271:24)
info Run CLI with --verbose flag for more details.
Error: Process completed with exit code 1.
```

**Comment by krystofwoldrich** [comment]
This looks like the same issue we are having with the simulator exec not being found.

- https://github.com/getsentry/sentry-react-native/pull/2475

I have started it here, but haven't got to it, to finish it yet.

**Comment by krystofwoldrich** [comment]
Adding another fail log.

https://github.com/getsentry/sentry-react-native/actions/runs/3069057118/jobs/4979620391

key error
```
FAIL test/e2e.test.ts (37.841 s)
  End to end tests for common events
    ✕ captureMessage (199 ms)
    ✕ captureException (23 ms)
    ✕ unhandledPromiseRejection (25 ms)
    ✕ close (25 ms)

  ● End to end tests for common events › captureMessage

    [init({"platformName":"Android","deviceName":"Android Emulator","app":"./android/app/build/outputs/apk/release/app-release.apk","newCommandTimeout":600000})] The environment you requested was unavailable.
    An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/runner/Library/Android/sdk/platform-tools/adb -P 5037 -s emulator-5554 install -r --no-incremental /Users/runner/work/sentry-react-native/sentry-react-native/sample/node_modules/appium-uiautomator2-server/apks/appium-uiautomator2-server-debug-androidTest.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability

      at node_modules/wd/lib/webdriver.js:157:15
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/wd/node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/wd/node_modules/request/request.js:1161:10)
      at IncomingMessage.<anonymous> (node_modules/wd/node_modules/request/request.js:1083:12)

  ● End to end tests for common events › captureMessage

    [hasElementByAccessibilityId("clearEventId")] Error response status: 9, , UnknownCommand - The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource. Selenium error: The requested resource could not be found, or a request was received using an HTTP method that is not supported by the mapped resource

      at Object.<anonymous>.exports.newError (node_modules/wd/lib/utils.js:152:13)
      at node_modules/wd/lib/callbacks.js:94:19
      at node_modules/wd/lib/webdriver.js:205:5
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/wd/node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/wd/node_modules/request/request.js:1161:10)
      at IncomingMessage.<anonymous> (node_modules/wd/node_modules/request/request.js:1083:12)


```

**Comment by krystofwoldrich** [comment]
Another example: https://github.com/getsentry/sentry-react-native/actions/runs/3081431111/jobs/4979966895

**Comment by krystofwoldrich** [comment]
@vaind Very likely you have seen this one, but for me it was new. Do you know what it could be?

```
An unknown server-side error occurred while processing the command. Original error: Command 'open -Fn /Applications/Xcode_13.2.1.app/Contents/Developer/Applications/Simulator.app --args -CurrentDeviceUDID 49F8F5E3-6987-4E54-A603-F75DDD103A16' exited with code 1
```

https://github.com/getsentry/sentry-react-native/actions/runs/3143209175/jobs/5107683045
