### ISSUE TITLE
iOS e2e test run fail on CI simulator due to "Unable to start WebDriverAgent session"

### ISSUE THREAD

**Issue by kahest** [getsentry/sentry-react-native#2482]
### Description

Occurs sometimes during `Run Tests` phase (`$ yarn test`): 

> An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: A new session could not be created. Details: Cannot launch io.sentry.sample application. Make sure the correct bundle identifier has been provided in capabilities and check the device log for possible crash report occurrences

See e.g. run
- https://github.com/getsentry/sentry-react-native/actions/runs/3059231607/jobs/4936368059

```
● End to end tests for common events › captureMessage

    [init({"app":"io.sentry.sample","deviceName":"iPhone 13","platformName":"iOS","newCommandTimeout":600000,"automationName":"XCUITest","derivedDataPath":"/Users/runner/work/sentry-react-native/sentry-react-native/sample/xc-build","showXcodeLog":true,"usePrebuiltWDA":true})] The environment you requested was unavailable.
    An unknown server-side error occurred while processing the command. Original error: Unable to start WebDriverAgent session because of xcodebuild failure: A new session could not be created. Details: Cannot launch io.sentry.sample application. Make sure the correct bundle identifier has been provided in capabilities and check the device log for possible crash report occurrences

      at node_modules/wd/lib/webdriver.js:157:15
      at Request._callback (node_modules/wd/lib/http-utils.js:89:7)
      at Request.self.callback (node_modules/wd/node_modules/request/request.js:185:[22](https://github.com/getsentry/sentry-react-native/actions/runs/3059231607/jobs/4936368059#step:18:23))
      at Request.<anonymous> (node_modules/wd/node_modules/request/request.js:1161:10)
      at IncomingMessage.<anonymous> (node_modules/wd/node_modules/request/request.js:1083:12)
...
```

**Comment by vaind** [comment]
Should be fixed by #2493 which now installs the app during the test phase (same as on Android), instead of relying on RN having installed it before.
