### ISSUE TITLE
Failed to deserialize object in list

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry-react-native#2503]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.5.0

**`react-native` version:** 0.67.4

**Are you using Expo?**
- [ ]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

sample app at 402f16e64115c5e6a804fec5c641295139104ce5

[Description]

from the adb log:
```
09-28 09:27:03.420  3642  3665 I ReactNativeJS: 'Sentry Logger [log]:', '[Tracing] Finishing ui.load transaction: Home.'
09-28 09:27:03.456  3642  3688 D Sentry  : onEvent fired for EnvelopeFileObserver with event type 8 on path: /data/user/0/io.sentry.sample/cache/sentry/db6c0289637c9b23a160b5d88201715785b1a5ad/outbox for file 8ebd2886-0c07-4bd2-ab26-52608cc417e8.
09-28 09:27:03.459  3642  3688 D Sentry  : Processing Envelope with 1 item(s)
09-28 09:27:03.461  3642  3688 E Sentry  : Failed to deserialize object in list.
09-28 09:27:03.461  3642  3688 E Sentry  : java.lang.IllegalStateException: Expected BEGIN_OBJECT but was END_ARRAY at line 1 column 1969 path $.breadcrumbs[0]
09-28 09:27:03.461  3642  3688 E Sentry  : 	at io.sentry.vendor.gson.stream.JsonReader.beginObject(JsonReader.java:392)
09-28 09:27:03.461  3642  3688 E Sentry  : 	at io.sentry.Breadcrumb$Deserializer.deserialize(Breadcrumb.java:457)
09-28 09:27:03.461  3642  3688 E Sentry  : 	at io.sentry.Breadcrumb$Deserializer.deserialize(Breadcrumb.java:452)
09-28 09:27:03.461  3642  3688 E Sentry  : 	at io.sentry.JsonObjectReader.nextList(JsonObjectReader.java:94)
09-28 09:27:03.461  3642  3688 E Sentry  : 	at io.sentry.SentryBaseEvent$Deserializer.deserializeValue(SentryBaseEvent.java:421)
09-28 09:27:03.461  3642  3688 E Sentry  : 	at io.sentry.protocol.SentryTransaction$Deserializer.deserialize(SentryTransaction.java:294)
09-28 09:27:03.461  3642  3688 E Sentry  : 	at io.sentry.protocol.SentryTransaction$Deserializer.deserialize(SentryTransaction.java:219)
09-28 09:27:03.461  3642  3688 E Sentry  : 	at io.sentry.JsonSerializer.deserialize(JsonSerializer.java:114)
09-28 09:27:03.461  3642  3688 E Sentry  : 	at io.sentry.OutboxSender.processEnvelope(OutboxSender.java:155)
09-28 09:27:03.461  3642  3688 E Sentry  : 	at io.sentry.OutboxSender.processFile(OutboxSender.java:72)
09-28 09:27:03.461  3642  3688 E Sentry  : 	at io.sentry.OutboxSender.processEnvelopeFile(OutboxSender.java:107)
09-28 09:27:03.461  3642  3688 E Sentry  : 	at io.sentry.android.core.EnvelopeFileObserver.onEvent(EnvelopeFileObserver.java:64)
09-28 09:27:03.461  3642  3688 E Sentry  : 	at android.os.FileObserver$ObserverThread.onEvent(FileObserver.java:163)
09-28 09:27:03.461  3642  3688 E Sentry  : 	at android.os.FileObserver$ObserverThread.observe(Native Method)
09-28 09:27:03.461  3642  3688 E Sentry  : 	at android.os.FileObserver$ObserverThread.run(FileObserver.java:113)
09-28 09:27:03.462  3642  3688 D Sentry  : Capturing transaction: 9f5f36750748436ab4b60667fd14ecf1
09-28 09:27:03.472  3642  3688 D Sentry  : Captured Envelope is already cached
```

[android-logs.zip](https://github.com/getsentry/sentry-react-native/files/9664627/android-logs.8.zip)

Not sure this is an actual issue, but it doesn't look related to the changes I'm making to the e2e tests.

**Comment by marandaneto** [comment]
Its just logging tho, reason is https://github.com/getsentry/sentry-java/issues/2151
