### ISSUE TITLE
Breaks pod install in expo managed tamagui project

### ISSUE THREAD

**Issue by lightchaser411** [getsentry/sentry-react-native#2660]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.10.1

**`react-native` version:** 0.70.5

**Are you using Expo?**
- [X]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

or

(`react-native-sentry`)
```
Sentry.config(
  'https://...@sentry.io/...'
  // other options
 ).install();
```

---
**I have following issue:**

Using sentry-expo successfully and receiving the no native warning. 
```
[sentry-expo] Disabling the Sentry Native SDK (all JS errors will still be reported).
To enable it, run 'yarn add @sentry/react-native' or 'npm install @sentry/react-native' in your project directory. To silence this warning, pass 'enableNative: false' to Sentry.init().
```

`expo install @sentry/react-native` and `yarn install @sentry/react-native` causes pod install to fail. I have tried deleting the ios directory and wiping node_modules. `yarn rm @sentry/react-native` causes pod install to successfully work again. We already have plenty of pure RN modules. 

```
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: Invalid `Podfile` file: 767: unexpected token at 'Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/zaid/jobs/moment/alpha/node_modules/chalk/source/index.js from /Users/zaid/jobs/moment/alpha/node_modules/@react-native-community/cli-config/build/readConfigFromDisk.js not supported.

Instead change the require of index.js in /Users/zaid/jobs/moment/alpha/node_modules/@react-native-community/cli-config/build/readConfigFromDisk.js to a dynamic import() which is available in all CommonJS modules.

    at _chalk (/Users/zaid/jobs/moment/alpha/node_modules/@react-native-community/cli-config/build/readConfigFromDisk.js:34:39)

    at readDependencyConfigFromDisk (/Users/zaid/jobs/moment/alpha/node_modules/@react-native-community/cli-config/build/readConfigFromDisk.js:94:19)

    at /Users/zaid/jobs/moment/alpha/node_modules/@react-native-community/cli-config/build/loadConfig.js:94:71

    at Array.reduce (<anonymous>)

    at loadConfig (/Users/zaid/jobs/moment/alpha/node_modules/@react-native-community/cli-config/build/loadConfig.js:91:134)

    at setupAndRun (/Users/zaid/jobs/moment/alpha/node_modules/@react-native-community/cli/build/index.js:200:45)

    at run (/Users/zaid/jobs/moment/alpha/node_modules/@react-native-community/cli/build/index.js:162:11)

    at Object.<anonymous> (/Users/zaid/jobs/moment/alpha/node_modules/@react-native-community/cli/build/bin.js:8:11)

info Run CLI with --verbose flag for more details.
'.

 #  from /Users/zaid/jobs/moment/alpha/apps/worlds-expo/ios/Podfile:14
 #  -------------------------------------------
 #    use_expo_modules!
 >    config = use_native_modules!
 #  
 #  -------------------------------------------
```

**Steps to reproduce:**
- Step 1: `npx create-tamagui-app@latest test`
- Step 2: Config sentry-expo in expo app without @sentry/react-native
- Step 3: Receive the warning 
- Step 4: Add @sentry/react-native
- Step 5: `expo run-ios`

**Comment by krystofwoldrich** [comment]
Hi,
thanks for the information.

I've tried a clean expo app and all works as expected. I followed https://docs.expo.dev/guides/using-sentry/.

```bash
npx create-expo-app my-app
cd my-app
npx expo install sentry-expo
npx expo install expo-application expo-constants expo-device expo-updates @sentry/react-native

# Add to App.js -> import * as Sentry from 'sentry-expo'; Sentry.init(...);

npm run ios
```

The tamagui app fails for me when I try to open it in iOS before adding Sentry.

```bash
npx create-tamagui-app@latest test
cd apps/expo
npx expo run:ios
⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod install` failed.
└─ Cause: CocoaPods could not find compatible versions for pod "EXFileSystem":
  In Podfile:
    EXFileSystem (from `../../../node_modules/expo-file-system/ios`)

Specs satisfying the `EXFileSystem (from `../../../node_modules/expo-file-system/ios`)` dependency were found, but they required a higher minimum deployment target.
```

Let me know if there was something missing in your steps. Does sentry-expo work in a clean expo project for you?

**Comment by krystofwoldrich** [comment]
@lightchaser411 Any updates?

**Comment by marandaneto** [comment]
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!
