### ISSUE TITLE
Investigate Invariant Violation and IllegalViewOperationException on the New Architecture

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-react-native#2671]
### Description

These errors are reported by RN SDK v5 in the release build of the new arch sample. The errors crash the app.

At first glance, there is no connection with our SDK but it needs to be investigated. 

```
Invariant Violation: requireNativeComponent: "RCTView" was not found in the UIManager.
  at invariant(node_modules/invariant/browser.js:38:15)
  at getNativeComponentAttributes(node_modules/react-native/Libraries/ReactNative/getNativeComponentAttributes.js:28:5)
  at ReactNativeViewConfigRegistry.register$argument_1(node_modules/react-native/Libraries/NativeComponent/NativeComponentRegistry.js:65:38)
  at exports.get(node_modules/react-native/Libraries/Renderer/shims/ReactNativeViewConfigRegistry.js:106:5)
  at completeWork(node_modules/react-native/Libraries/Renderer/implementations/ReactFabric-prod.js:5555:16)
  at completeUnitOfWork(node_modules/react-native/Libraries/Renderer/implementations/ReactFabric-prod.js:7109:58)
  at performUnitOfWork(node_modules/react-native/Libraries/Renderer/implementations/ReactFabric-prod.js:7099:19)
  at workLoopSync(node_modules/react-native/Libraries/Renderer/implementations/ReactFabric-prod.js:7090:55)
  at renderRootSync(node_modules/react-native/Libraries/Renderer/implementations/ReactFabric-prod.js:7072:7)
  at recoverFromConcurrentError(node_modules/react-native/Libraries/Renderer/implementations/ReactFabric-prod.js:6700:10)
  at performConcurrentWorkOnRoot(node_modules/react-native/Libraries/Renderer/implementations/ReactFabric-prod.js:6564:23)
  at G(node_modules/scheduler/cjs/scheduler.production.min.js:13:205)
  at J(node_modules/scheduler/cjs/scheduler.production.min.js:14:128)
  at apply(native)
  at queueReactNativeMicrotask(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:248:35)
  at _callTimer(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:114:15)
  at _callReactNativeMicrotasksPass(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:162:41)
  at callReactNativeMicrotasks(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:413:12)
  at __callReactNativeMicrotasks(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:390:7)
  at flushedQueue(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:132:7)
  at __guard(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:366:7)
  at flushedQueue(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:131:18)
```

```
com.facebook.react.uimanager.IllegalViewOperationException: No ViewManager found for class RCTView
    at com.facebook.react.uimanager.ViewManagerRegistry.get(ViewManagerRegistry.java:68)
    at com.facebook.react.fabric.mounting.SurfaceMountingManager.createViewUnsafe(SurfaceMountingManager.java:857)
    at com.facebook.react.fabric.mounting.SurfaceMountingManager.preallocateView(SurfaceMountingManager.java:1250)
    at com.facebook.react.fabric.mounting.mountitems.PreAllocateViewMountItem.execute(PreAllocateViewMountItem.java:63)
    at com.facebook.react.fabric.mounting.MountItemDispatcher.executeOrEnqueue(MountItemDispatcher.java:351)
    at com.facebook.react.fabric.mounting.MountItemDispatcher.dispatchPreMountItems(MountItemDispatcher.java:330)
    at com.facebook.react.fabric.FabricUIManager$DispatchUIFrameCallback.doFrameGuarded(FabricUIManager.java:1248)
    at com.facebook.react.fabric.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:31)
    at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:175)
    at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:85)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
    at android.view.Choreographer.doCallbacks(Choreographer.java:899)
    at android.view.Choreographer.doFrame(Choreographer.java:827)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at android.app.ActivityThread.main(ActivityThread.java:7898)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by krystofwoldrich** [comment]
I could not reproduce it with clean app and latest v5 alpha of the SDK. Likely relates to our sample app settings.
