### ISSUE TITLE
captureMessage tries to import the message string as a js module if the message prefix is "http"

### ISSUE THREAD

**Issue by jensa** [getsentry/sentry-react-native#2774]
**OS:**
- [ ]  Windows
- [ x]  MacOS
- [ ]  Linux

**Platform:**
- [x ]  iOS
- [ ]  Android

**SDK:**
- [x ]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.2.2

**`react-native` version:** 0.69.6

**Are you using Expo?**
- [x ]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x ]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

import * as Sentry from "sentry-expo";

Sentry.init({
  dsn: config().SENTRY_DSN,
  enableInExpoDevelopment: true,
  environment: "dev"
});

---
**I have following issue:**

When I call Sentry.Native.captureMessage() with any string that begins with "http", the metro bundler crashes with the following error (this specific error used the exact string "http", but any string with this prefix will generate an error where it's trying to find a module with the same name as the string provided):

Error: Unable to resolve module ./http from /Users/jensarvidsson/leia/code/app/.:

None of these files exist:
  * http(.native|.native.ts|.ts|.native.tsx|.tsx|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.jsx,js,ts,tsx,cjs,json|.jsx,js,ts,tsx,cjs,json)
  * http/index(.native|.native.ts|.ts|.native.tsx|.tsx|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.jsx,js,ts,tsx,cjs,json|.jsx,js,ts,tsx,cjs,json)
    at ModuleResolver.resolveDependency (/Users/jensarvidsson/leia/code/app/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:136:15)
    at DependencyGraph.resolveDependency (/Users/jensarvidsson/leia/code/app/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at /Users/jensarvidsson/leia/code/app/node_modules/metro/src/lib/transformHelpers.js:129:24
    at Server._resolveRelativePath (/Users/jensarvidsson/leia/code/app/node_modules/metro/src/Server.js:1137:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Server._explodedSourceMapForURL (/Users/jensarvidsson/leia/code/app/node_modules/metro/src/Server.js:1088:35)
    at async Promise.all (index 0)
    at async Server._symbolicate (/Users/jensarvidsson/leia/code/app/node_modules/metro/src/Server.js:1039:26)
    at async Server._processRequest (/Users/jensarvidsson/leia/code/app/node_modules/metro/src/Server.js:443:7)
    
    if I change the message string to be anything else (including "htt" and similar), this error does not happen
**Steps to reproduce:**
- Step 1
Call Sentry.Native.captureMessage("http")

**Actual result:**

The error report above in the bundler logs

**Expected result:**

no error and the string "http" to be sent as a message to sentry

**Comment by krystofwoldrich** [comment]
Hi, thank you for the information,
what workflow are you using `bare` or `managed`? Are you using `expo-dev-client` package?

Does it happen in `production`  or only in the dev environment?
