### ISSUE TITLE
Fix modules collector on Windows

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry-react-native#3074]
### Description

Modules collector tests fail on Windows. Unknown if it's the tests or the collector itself.

https://github.com/getsentry/sentry-react-native/blob/d7401ac44acf524fe4d9a6a525f2cc13c70ce9e5/test/tools/collectModules.test.ts#L11

```
 FAIL  test/tools/collectModules.test.ts
  ● collectModules › should collect modules from multiple modules paths

    expect(received).toEqual(expected) // deep equality

    - Expected  - 6
    + Received  + 1

    - Object {
    -   "module-1": "module-1-version",
    -   "module-2": "unknown",
    -   "module-3": "module-3-version",
    -   "root-module": "root-module-version",
    - }
    + Object {}

      21 |     );
      22 |
    > 23 |     expect(modules).toEqual({
         |                     ^
      24 |       'root-module': 'root-module-version',
      25 |       'module-1': 'module-1-version',
      26 |       'module-2': 'unknown',

      at Object.toEqual (test/tools/collectModules.test.ts:23:21)

  ● collectModules › should collect modules from single module path

    expect(received).toEqual(expected) // deep equality

    - Expected  - 4
    + Received  + 1

    - Object {
    -   "module-1": "module-1-version",
    -   "module-2": "unknown",
    - }
    + Object {}

      40 |     );
      41 |
    > 42 |     expect(modules).toEqual({
         |                     ^
      43 |       'module-1': 'module-1-version',
      44 |       'module-2': 'unknown',
      45 |     });

      at Object.toEqual (test/tools/collectModules.test.ts:42:21)
```

**Comment by kahest** [comment]
@krystofwoldrich closing as stale/outdated and low impact, please reopen if still relevant and significant impact
