### ISSUE TITLE
Broken Stacktrace for react-native app (on premise)

### ISSUE THREAD

**Issue by tom-krusch** [getsentry/sentry-react-native#3139]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** ^5.6.0

**`react-native` version:** 0.69.9

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [x]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
 Sentry.init({
    dsn: xxx,
    ignoreErrors: ['Network request failed', 'BGTaskSchedulerErrorDomain'],
    release: `${DeviceInfo.getBundleId()}@${DeviceInfo.getVersion()}+${DeviceInfo.getBuildNumber()}`,
    dist: DeviceInfo.getBuildNumber(),
  });
```

---
**I have following issue:**

Instead of the actual location in the code, I always get the following as a stack trace for each error:
The source maps have been successfully uploaded and the UI does not give any error/warning about it.

**Actual result:**

```
TypeError: Cannot read property 'slice' of undefined
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at apply(native)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
```
or
```
TypeError: undefined is not a function
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at apply(native)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at apply(native)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at apply(native)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at forEach(native)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at apply(native)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
  at render(node_modules/redux-persist/lib/integration/react.js:99:9)
```

But theoretically I would expect to see in the stacktrace in which file and line the error occurred

**Comment by krystofwoldrich** [comment]
Hi, 
thank you for the message.

How do you upload the source maps? Manually by `sentry-cli`, can you share an example? Or automatically during the iOS/Android builds?

When you open the Release Detail page, do you see your uploaded source maps? Make sure to check that it's the same release as the one reported by the application. You can click thru the release link on the issue page.

**Comment by tom-krusch** [comment]
during the build process i do the following things:

1. create sentry version string 
`sentry_version = <identifier> + '@' + <version> + '+' + <build_number>`
2. create Bundle:
```
npx react-native bundle --platform ios --dev false --entry-file index.ios.js --reset-cache --bundle-output main.jsbundle --sourcemap-output main.jsbundle.map --minify false

ios/Pods/hermes-engine/destroot/bin/hermesc -O -emit-binary -output-source-map -out=main.jsbundle.hbc main.jsbundle

rm -f main.jsbundle

mv main.jsbundle.hbc main.jsbundle

mv main.jsbundle.map main.jsbundle.packager.map

node node_modules/react-native/scripts/compose-source-maps.js main.jsbundle.packager.map main.jsbundle.hbc.map -o main.jsbundle.map
```
4. create release
`sentry-cli --url <our domain> releases new #{sentry_version} -o <org> -p <project> --auth-token <auth_token>`
5. source maps hochladen
`sentry-cli --url <our domain> sourcemaps upload -r #{sentry_version} -d <build_number> --auth-token <auth_token> -o <org> -p <project> --log-level=debug --strip-prefix <prefix> .`
6. finalize release
`sentry-cli --url <our domain> releases finalize #{sentry_version} -o <org> -p <project> --auth-token <auth_token>`

As described above, Sentry is initialized like this:
 ```
Sentry.init({
    dsn: xxx,
    ignoreErrors: ['Network request failed', 'BGTaskSchedulerErrorDomain'],
    release: `${DeviceInfo.getBundleId()}@${DeviceInfo.getVersion()}+${DeviceInfo.getBuildNumber()}`,
    dist: DeviceInfo.getBuildNumber(),
  });
```
Thus, "dist" and "release" are identical to the one in the build process

On the Release Detail Page I have the following entries (the dist/Build-Number is shown with each entry)
~/main.jsbundle ... 0 B
~/main.jsbundle.hbc.map ... 7.5 MiB
~/main.jsbundle.map ... 29.5 MiB
~/main.jsbundle.packager.map ... 41.5 MiB
This is then also the release I find when I click through from the issue

**Comment by krystofwoldrich** [comment]
Thank you for the detailed steps.

Depending on the way you build your app you might not need to create the Hermes bundle and combined source maps.

Please see this guide from the docs with further explanation https://docs.sentry.io/platforms/react-native/manual-setup/hermes/#compile-source-maps

**Comment by krystofwoldrich** [comment]
Have you tried the combined source map locally with `metro-symbolicate`? That way you can verify that the source map is created correctly.

https://reactnative.dev/docs/0.69/symbolication

**Comment by krystofwoldrich** [comment]
Closing this due to inactivity. If this is still an issue feel free to comment here or open a new issue if the context changed.
