### ISSUE TITLE
Sentry warning when running "setup-ios-permissions"

### ISSUE THREAD

**Issue by felipejoribeiro** [getsentry/sentry-react-native#3261]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.7.1

**`react-native` version:** 0.68.1

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

No issue in sentry.io

**Configuration:**

Not relevant... 

**I have following issue:**

When I run `react-native setup-ios-permissions` i get the following output:

```
warn Package @sentry/react-native contains invalid configuration: "dependency.platforms.ios.sharedLibraries" is not allowed,"dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.
error: unknown command 'setup-ios-permissions'
```

To further investigate the warning, i did run. the `react-native config` command, and i got the following output:

```
error Cannot read properties of undefined (reading 'configurations').
TypeError: Cannot read properties of undefined (reading 'configurations')
    at Object.dependencyConfig (/Users/fejori/Work/snackin/mobile-app/node_modules/@react-native-community/cli-platform-ios/build/config/index.js:102:37)
    at /Users/fejori/.nvm/versions/node/v16.15.0/lib/node_modules/react-native/node_modules/@react-native-community/cli-config/build/loadConfig.js:35:61
    at Array.reduce (<anonymous>)
    at getDependencyConfig (/Users/fejori/.nvm/versions/node/v16.15.0/lib/node_modules/react-native/node_modules/@react-native-community/cli-config/build/loadConfig.js:31:51)
    at Object.get @amplitude/react-native [as @amplitude/react-native] (/Users/fejori/.nvm/versions/node/v16.15.0/lib/node_modules/react-native/node_modules/@react-native-community/cli-config/build/loadConfig.js:101:20)
    at /Users/fejori/.nvm/versions/node/v16.15.0/lib/node_modules/react-native/node_modules/@react-native-community/cli-config/build/commands/config.js:15:51
    at Array.forEach (<anonymous>)
    at filterConfig (/Users/fejori/.nvm/versions/node/v16.15.0/lib/node_modules/react-native/node_modules/@react-native-community/cli-config/build/commands/config.js:14:38)
    at Object.func (/Users/fejori/.nvm/versions/node/v16.15.0/lib/node_modules/react-native/node_modules/@react-native-community/cli-config/build/commands/config.js:25:32)
    at Command.handleAction (/Users/fejori/.nvm/versions/node/v16.15.0/lib/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:111:23)
```

**Steps to reproduce:**
Not sure about that.

**Actual result:**

Received said warning.

**Expected result:**

No warnings.

**Comment by krystofwoldrich** [comment]
Hi,
thank you for the message and the details.

This configuration was updated in https://github.com/getsentry/sentry-react-native/releases/tag/5.0.0. Version 5 of the Sentry SDK is included in https://github.com/expo/sentry-expo/releases/tag/v7.0.0 if you are using `sentry-expo`.

If the warning still appears please comment here and we can reopen the issue.
