### ISSUE TITLE
Expo: Sentry/HybridSDK 8.17.1 not found in specs

### ISSUE THREAD

**Issue by jetaggart** [getsentry/sentry-react-native#3544]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.16.0

**`react-native` version:** 0.73.2

**Are you using Expo?**
- [x]  Yes (50.0.2)
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**
Default steps from here: 
https://docs.expo.dev/guides/using-sentry/

---
**I have the following issue:**

Fails to build with below error:

**Steps to reproduce:**
- fresh project on expo 50, then follow steps here: https://docs.expo.dev/guides/using-sentry/
- build with: `eas build --platform ios --local --profile staging`

**Actual result:**
```
[INSTALL_PODS] [!] CocoaPods could not find compatible versions for pod "Sentry/HybridSDK":
[INSTALL_PODS]   In Podfile:
[INSTALL_PODS]     RNSentry (from `../../../node_modules/@sentry/react-native`) was resolved to 5.16.0, which depends on
[INSTALL_PODS]       Sentry/HybridSDK (= 8.17.1)
[INSTALL_PODS] None of your spec sources contain a spec satisfying the dependency: `Sentry/HybridSDK (= 8.17.1)`.
[INSTALL_PODS] You have either:
[INSTALL_PODS]  * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
[INSTALL_PODS]  * mistyped the name or version.
[INSTALL_PODS]  * not added the source repo that hosts the Podspec to your Podfile.
[INSTALL_PODS] [!] `<PBXResourcesBuildPhase UUID=`13B07F8E1A680F5B00A75B9A`>` attempted to initialize an object with an unknown UUID. `602CE8A66E5B48A4B03DEB5B` for attribute: `files`. This can be the result of a merge and the unknown UUID is being discarded.
[INSTALL_PODS] 
```

**Expected result:**

Successful build

**Comment by jetaggart** [comment]
Maybe this is a monorepo issue? I have a yarn workspaces setup following this guide: https://docs.expo.dev/guides/monorepos/

**Comment by krystofwoldrich** [comment]
Hi @jetaggart,
thank you for the message and the error log.

Have you tried `pod repo update` and `pod install --repo-update`? And then `eas build --platform ios --local --profile staging` again?

**Comment by jetaggart** [comment]
@krystofwoldrich I can't run those commands as I'm using fulling managed expo, there is no ios/android folder.

**Comment by krystofwoldrich** [comment]
You can run `pod repo update` which updates local repositories on your machine.

It relates to your Cocoapods install not directly to the native project.

**Comment by jetaggart** [comment]
Ah that was it, my bad. I didn't realize you could still interact with cocoapods without a podspec. Thank you!

**Comment by williamdes** [comment]
It sill does not work, I tried all pod update methods. Nothing works 
Since https://github.com/getsentry/sentry-react-native/compare/5.22.2...5.22.3#diff-d3ef6731f83385c9d45e9358dd2c25ede9d8de8762ae54e6917037ecdbca440eR36

**Comment by EliG-TA** [comment]
I get a similar issue. 

**Here is the error output I get in the terminal after running `npx expo prebuild -p ios` and then `npx expo run:ios`**
```
[!] CocoaPods could not find compatible versions for pod "Sentry/HybridSDK":
  In Podfile:
    RNSentry (from `../node_modules/@sentry/react-native`) was resolved to 5.24.1, which depends on
      Sentry/HybridSDK (= 8.29.1)

None of your spec sources contain a spec satisfying the dependency: `Sentry/HybridSDK (= 8.29.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
Couldn't install Pods. Updating the Pods project and trying again...
- Couldn't install Pods. Updating the Pods project and trying again...
> pod install --repo-update
- Couldn't install Pods. Updating the Pods project and trying again...
Using Expo modules
```

**Here is the RNSentry.podspec file code:**
```

require_relative './scripts/sentry_utils.rb'
require 'json'
version = JSON.parse(File.read('package.json'))["version"]

rn_package = parse_rn_package_json()
rn_version = get_rn_version(rn_package)
is_hermes_default = is_hermes_default(rn_version)
is_profiling_supported = is_profiling_supported(rn_version)

folly_flags = ' -DFOLLY_NO_CONFIG -DFOLLY_MOBILE=1 -DFOLLY_USE_LIBCPP=1'
folly_compiler_flags = folly_flags + ' ' + '-Wno-comma -Wno-shorten-64-to-32'

is_new_arch_enabled = ENV["RCT_NEW_ARCH_ENABLED"] == "1"
is_using_hermes = (ENV['USE_HERMES'] == nil && is_hermes_default) || ENV['USE_HERMES'] == '1'
new_arch_enabled_flag = (is_new_arch_enabled ? folly_compiler_flags + " -DRCT_NEW_ARCH_ENABLED" : "")
sentry_profiling_supported_flag = (is_profiling_supported ? " -DSENTRY_PROFILING_SUPPORTED=1" : "")
other_cflags = "$(inherited)" + new_arch_enabled_flag + sentry_profiling_supported_flag

Pod::Spec.new do |s|
  s.name           = 'RNSentry'
  s.version        = version
  s.license        = 'MIT'
  s.summary        = 'Official Sentry SDK for react-native'
  s.author         = 'Sentry'
  s.homepage       = "https://github.com/getsentry/sentry-react-native"
  s.source         = { :git => 'https://github.com/getsentry/sentry-react-native.git', :tag => "#{s.version}"}

  s.ios.deployment_target = "11.0"
  s.osx.deployment_target = "10.13"
  s.tvos.deployment_target = "11.0"
  s.visionos.deployment_target = "1.0" if s.respond_to?(:visionos)

  s.preserve_paths = '*.js'

  s.dependency 'React-Core'
  s.dependency 'Sentry/HybridSDK', '8.29.1'

  s.source_files = 'ios/**/*.{h,m,mm}'
  s.public_header_files = 'ios/RNSentry.h'

  s.compiler_flags = other_cflags
  \# This guard prevent to install the dependencies when we run `pod install` in the old architecture.
  if is_new_arch_enabled then
    s.pod_target_xcconfig = {
        "HEADER_SEARCH_PATHS" => "\"$(PODS_ROOT)/boost\"",
        "CLANG_CXX_LANGUAGE_STANDARD" => "c++17"
    }
    s.dependency "React-Codegen"
    s.dependency "RCT-Folly"
    s.dependency "RCTRequired"
    s.dependency "RCTTypeSafety"
    s.dependency "ReactCommon/turbomodule/core"
  end

  if is_using_hermes then
    s.dependency 'React-hermes'
    s.dependency 'hermes-engine'
  end
end
```

**Comment by krystofwoldrich** [comment]
@williamdes I'm sorry to hear that, could you open a new issue with the error you are getting?

**Comment by krystofwoldrich** [comment]
@EliG-TA Have you tried updating your local pod sources?

Does this work?
```
npx expo prebuild --no-install -p ios
cd ios
pod repo update
pod install
```

**Comment by EliG-TA** [comment]
> pod repo update

Thank you @krystofwoldrich! I was not expecting such a quick response.

I ran `npx expo prebuild --no-install -p ios` and that worked fine, however when running `cd ios` from the project root directory and then `pod repo update`, here is the error output I get:

```
[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=dlopen%28%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.5%2Flib%2Fffi_c.bundle%2C+0x0009%29%3A+tried%3A+%27%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.5%2Flib%2Fffi_c.bundle%27+%28mach-o+file%2C+but+is+an+incompatible+architecture+%28have+%27arm64%27%2C+need+%27x86_64h%27+or+%27x86_64%27%29%29%2C+%27%2FSystem%2FVolumes%2FPreboot%2FCryptexes%2FOS%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.5%2Flib%2Fffi_c.bundle%27+%28no+such+file%29%2C+%27%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.5%2Flib%2Fffi_c.bundle%27+%28mach-o+file%2C+but+is+an+incompatible+architecture+%28have+%27arm64%27%2C+need+%27x86_64h%27+or+%27x86_64%27%29%29+-+%2FLibrary%2FRuby%2FGems%2F2.6.0%2Fgems%2Fffi-1.15.5%2Flib%2Fffi_c.bundle&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Searching for inspections failed: undefined method `map' for nil:NilClass
```
Not sure if this gives you enough info, however this may also shed some light as this was also in the output:

### Error

```
LoadError - dlopen(/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle, 0x0009): tried: '/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (no such file), '/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')) - /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi.rb:5:in `rescue in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/ethon-0.16.0/lib/ethon.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:78:in `deprecated_local_podspecs'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:60:in `preheat_existing_files'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.15.2/lib/cocoapods-core/cdn_source.rb:257:in `update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/sources_manager.rb:144:in `block (3 levels) in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/sources_manager.rb:143:in `block (2 levels) in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/sources_manager.rb:142:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/sources_manager.rb:142:in `block in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/sources_manager.rb:140:in `open'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/sources_manager.rb:140:in `update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command/repo/update.rb:23:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by williamdes** [comment]
> @williamdes I'm sorry to hear that, could you open a new issue with the error you are getting?

I did not find in my history, but on one issue or PR it was mentionned this is because it requires a newer react native version

**Comment by EliG-TA** [comment]
@krystofwoldrich Any idea of what caused the issue and if there can be a patch for this in the next update for sentry-react-native?

**Comment by krystofwoldrich** [comment]
@williamdes @EliG-TA From the latest comments I see you found the pods issue unrelated to the Sentry SDK version and resolved it.

Is there still something unresolved on our side?

**Comment by EliG-TA** [comment]
@williamdes I guess so. Not sure if this is more of a widespread problem, as I did feel it was more of a hacky solution.

**Comment by williamdes** [comment]
Hi devs,

I will know on the next package bump session, but it seems like at the time of commenting it did not work, see: https://github.com/getsentry/sentry-react-native/issues/3544#issuecomment-2150459000
