### ISSUE TITLE
Sentry CLI binary for this platform/architecture not found

### ISSUE THREAD

**Issue by quinlanj** [getsentry/sentry-react-native#3554]
**OS:**
- [x]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 0.0.0

**`react-native` version:** 0.0.0

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**
`@sentry/react-native`: 5.16.0
`@sentry/cli`: 2.23.0

**I have the following issue:**
Expo users upgrading to SDK 50 are running into this issue

```
/home/expo/workingdir/build/frontend/node_modules/@sentry/cli/js/helper.js:116
      throw new Error(`Sentry CLI binary for this platform/architecture not found!
      ^
Error: Sentry CLI binary for this platform/architecture not found!
It seems like none of the "@sentry/cli" package's optional dependencies got installed. Please make sure your package manager is configured to install optional dependencies. If you are using npm to install your dependencies, please don't set the "--no-optional" or "--omit=optional" flags. Sentry CLI needs the "optionalDependencies" feature in order to install its binary.
    at getBinaryPath (/home/expo/workingdir/build/frontend/node_modules/@sentry/cli/js/helper.js:116:13)
    at Object.<anonymous> (/home/expo/workingdir/build/frontend/node_modules/@sentry/cli/js/helper.js:129:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/home/expo/workingdir/build/frontend/node_modules/@sentry/cli/js/index.js:4:16)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
Node.js v18.18.0
Task :app:createBundleReleaseJsAndAssets_SentryUploadCleanUp SKIPPED
Task :expo:extractReleaseAnnotations
Task :expo-modules-core:buildCMakeRelWithDebInfo[x86]
```

**Comment by quinlanj** [comment]
The recommended fix is to upgrade to `@sentry/react-native` 5.17.0, where the newest version of the cli will manually download the missing binaries https://github.com/getsentry/sentry-cli/issues/1849#issuecomment-1876921227

**Comment by krystofwoldrich** [comment]
Thank you @quinlanj.

**Comment by quinlanj** [comment]
If that does not work, a common cause is this[ npm bug](https://github.com/npm/cli/issues/4828#issue-1221585027) if the user has a `package-lock.json` that only has the optional dependency for their os declared, so when it is run on a machine with a different os (like a CI builder), the error is thrown. To workaround, remove `node_modules` and `package-lock.json` and reinstall dependencies again

**Comment by stereodenis** [comment]
I try to run it on CI, but got this

[11:02:58]: ▸ Error: Sentry CLI binary for this platform/architecture not found!
[11:02:58]: ▸ The "@sentry/cli-linux-x64" package is installed, but for the current platform, you should have the "@sentry/cli-darwin" package installed instead. This usually happens if the "@sentry/cli" package is installed on one platform (for example Windows or MacOS) and then the "node_modules" folder is reused on another operating system (for example Linux in Docker).
[11:02:58]: ▸ To fix this, avoid copying the "node_modules" folder, and instead freshly install your dependencies on the target system. You can also configure your package manager to install the right package. For example, yarn has the "supportedArchitectures" feature: https://yarnpkg.com/configuration/yarnrc/#supportedArchitecture.

**Comment by jamesmcn1** [comment]
Yeah I can confirm adding this to .yarnrc.yml has fixed the issue. Its because on Bitrise we were downloading node modules on a MacOs stack then doing our Android build on a linux machine.

```
supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux
```
