### ISSUE TITLE
No static method getCurrentScope()Lio/sentry/Scope

### ISSUE THREAD

**Issue by kosiken** [getsentry/sentry-react-native#3560]
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.17.0

**`react-native` version:** 0.73.2

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  beforeSend: (event) => {
    if (
      !event.message?.includes(
        'ViewPropTypes will be removed from React Native, along with all other PropTypes'
      ) &&
      event.environment !== 'development'
    ) {
      return event
    }
  },
  debug: false,
  enableAutoSessionTracking: true,
  enableInExpoDevelopment: true,
  environment: __DEV__
    ? 'development'
    : bundleId?.includes('qa')
    ? 'QA'
    : 'production'
});
```

or

(`react-native-sentry`)
```
Sentry.config(
  'https://...@sentry.io/...'
  // other options
 ).install();
```

---
**I have the following issue:**
Whenever we try to capture an exception on android our app crashes with the following error 

```
java.lang.RuntimeException: Could not invoke RNSentry.fetchNativeDeviceContexts
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:381)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:149)
	at com.facebook.jni.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:234)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:149) 
	at com.facebook.jni.NativeRunnable.run(Native Method) 
	at android.os.Handler.handleCallback(Handler.java:958) 
	at android.os.Handler.dispatchMessage(Handler.java:99) 
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
	at android.os.Looper.loopOnce(Looper.java:205) 
	at android.os.Looper.loop(Looper.java:294) 
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:234) 
	at java.lang.Thread.run(Thread.java:1012) 
Caused by: java.lang.NoSuchMethodError: No static method getCurrentScope()Lio/sentry/Scope; in class Lio/sentry/android/core/InternalSentrySdk; or its super classes (declaration of 'io.sentry.android.core.InternalSentrySdk' appears in /data/app/~~2nzInAiV4ly_ySwIfVJivw==/com.rise.mobile.qa-zgV3LF0BAc69hiywYfjipA==/base.apk!classes7.dex)
	at io.sentry.react.RNSentryModuleImpl.fetchNativeDeviceContexts(RNSentryModuleImpl.java:687)
	at io.sentry.react.RNSentryModule.fetchNativeDeviceContexts(RNSentryModule.java:118)
```

**Steps to reproduce:**
- Install Sentry/react native and set android compile sdk to 34
- Run application and try to call Sentry.captureException

**Actual result:**

App crashes with the above error

**Expected result:**

App should not crash

**Comment by krystofwoldrich** [comment]
Hi @kosiken,
thank you for the message, I've identified this as the cause of the error.

```
No static method getCurrentScope()Lio/sentry/Scope; in class Lio/sentry/android/core/InternalSentrySdk; or its super classes (declaration of 'io.sentry.android.core.InternalSentrySdk' appears in /data/app/~~2nzInAiV4ly_ySwIfVJivw==/com.rise.mobile.qa-zgV3LF0BAc69hiywYfjipA==/base.apk!classes7.dex)
```

Could you let me know if you are using Sentry Android Gradle Plugin? What version of `sentry-android` do you have installed? You seem to have `sentry-android` version 7 but the RN SDK requires version 6.

Here is how to fix this: https://github.com/getsentry/sentry-react-native/issues/3497#issuecomment-1889566285

**Comment by krystofwoldrich** [comment]
Would you be able to share a minimal reproducible example?

**Comment by jayshah123** [comment]
I face the same crash with following:
`@sentry/react-native` upgraded from `5.5.0` to `5.10.0`. The Changelog does not seem to indicate any upgrade steps.
RN Version: `0.72.7`

On android I use following (not changed while upgrading from `5.5.0` to `5.10.0`:
```
// app/build.gradle
plugins {
  id 'io.sentry.android.gradle' version '4.2.0'
}
```

**Comment by jayshah123** [comment]
Also, once trying this fix: https://github.com/getsentry/sentry-react-native/issues/3497#issuecomment-1889566285, I don't see any events landing up in dashboard. Is there a checklist to verify the events being ingested all the way from sdk to sentry.io dashboard. I've already tried `debug: true`, which says sdk initialized as expected but nothing other than that. I expect atleast to show a warning locally when I call `captureException` method but it does not make its way/or makes its way to sentry cloud when I have `debug: true`.

**Comment by krystofwoldrich** [comment]
@jayshah123 Thank you for the message.

Import of `AppStartMetrics` in RN SDK was added in https://github.com/getsentry/sentry-react-native/releases/tag/5.19.0, possibly you used the latest SDK, not `5.5.0`?

We don't keep compatibility table as the RN SDK includes `sentry-android` as explicit dependency https://github.com/getsentry/sentry-react-native/blob/cbee1f9c5379a7ac3b50a8b13741f34ed5c63a06/android/build.gradle#L57

Please keep `autoInstallation false` to avoid auto installing incompatible versions and make sure to clean build the android application when changing the package version to ensure compatible native code is used.

**Comment by jayshah123** [comment]
Hey thanks for the quick update.

I don't see any crashes on downgrade + `autoInstallation false`, but don't see any event ending up in dashboard either.
Is there a checklist/flag to debug events not flowing to the dashboard from the sdk?

**Comment by krystofwoldrich** [comment]
When `debug: true` you can see details about what the SDK sends in logcat. The native layer takes care of sending the data to Sentry.

To check the last step before the data leaves the JS layer, you can log the events in `beforeSend` callback.

**Comment by krystofwoldrich** [comment]
Closing in favor of https://github.com/getsentry/sentry-react-native/issues/3671 which fixes the root cause of the issue.
