### ISSUE TITLE
[Expo SDK50] npx sentry-expo-upload-sourcemaps dist throws error, sentry-cli is not recognized as an internal or external command 

### ISSUE THREAD

**Issue by leons1767** [getsentry/sentry-react-native#3613]
**OS:**
- [X]  Windows
- [ ]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [ ]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.17.0

**`react-native` version:** 0.73.4

**Are you using Expo?**
- [X]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
  Sentry.init({
    dsn: process.env.SENTRY_DSN,
    enabled: !__DEV__, 
    debug: false 
  });
```

---
**I have the following issue:**

`npx sentry-expo-upload-sourcemaps dist` returns below error
```
⬆️ Uploading dist\_expo\static\js\ios\index-***.hbc bundle and sourcemap...
'D:\***\***\node_modules\@sentry\cli\bin\sentry-cli' is not recognized as an internal or external command,
operable program or batch file.
node:child_process:965
    throw err;
    ^

Error: Command failed: D:\***\***\node_modules\@sentry\cli\bin\sentry-cli sourcemaps upload --debug-id-reference dist\_expo\static\js\ios\index-***.hbc dist\_expo\static\js\ios\index-***.hbc.map
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at Object.<anonymous> (D:\***\***\node_modules\@sentry\react-native\scripts\expo-upload-sourcemaps.js:151:3)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 18904,
  stdout: null,
  stderr: null
}

Node.js v21.6.2

```

**Steps to reproduce:**
1. Run `eas update --branch production --platform ios` to produce new sourcemaps in dist folder
2. Run `npx sentry-expo-upload-sourcemaps dist`

- Installed using `npx expo install @sentry/react-native` version 5.17.0.
- Tried updating @sentry/react-native to version 5.19.0, same error.
- `eas build` automatic sourcemaps upload is working fine

**Actual result:**

```
⬆️ Uploading dist\_expo\static\js\ios\index-***.hbc bundle and sourcemap...
'D:\***\***\node_modules\@sentry\cli\bin\sentry-cli' is not recognized as an internal or external command,
operable program or batch file.
node:child_process:965
    throw err;
    ^

Error: Command failed: D:\***\***\node_modules\@sentry\cli\bin\sentry-cli sourcemaps upload --debug-id-reference dist\_expo\static\js\ios\index-***.hbc dist\_expo\static\js\ios\index-***.hbc.map
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at Object.<anonymous> (D:\***\***\node_modules\@sentry\react-native\scripts\expo-upload-sourcemaps.js:151:3)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 18904,
  stdout: null,
  stderr: null
}

Node.js v21.6.2

```

**Expected result:**

New sourcemaps successfully updated to sentry.io

**Comment by Bi0max** [comment]
Having the same bug at the moment

**Comment by krystofwoldrich** [comment]
Hi @Bi0max, thank you for the message, what os are you on?

**Comment by Bi0max** [comment]
Hi, Kryštof, I'm on Windows 11

**Comment by kahest** [comment]
@leons1767 thanks for confirming - we didn't repicate this yet but will tackle this soon

**Comment by CteixeiraPW** [comment]
I have the same error when I run the command `npx sentry-expo-upload-sourcemaps dist` and I tried on CMD, Git Batch, PowerShell (old and new version), on Windows 11. Any suggestion?

**Comment by krystofwoldrich** [comment]
@CteixeiraPW Thank you for the extra details. We will update this issue with more information soon.
