### ISSUE TITLE
AppLifecycleIntegration.removeObserver NullPointerException (observer is null) 

### ISSUE THREAD

**Issue by Qdafengzi** [getsentry/sentry-react-native#3781]
Android

**SDK:**
`"@sentry/react-native": "4",` 
`"react-native": "0.72.4",`

```
java.lang.NullPointerException: Parameter specified as non-null is null: method androidx.lifecycle.LifecycleRegistry.removeObserver, parameter observer
at androidx.lifecycle.LifecycleRegistry.removeObserver(Unknown Source:3)
at io.sentry.android.core.AppLifecycleIntegration.removeObserver(AppLifecycleIntegration.java:112)
at io.sentry.android.core.AppLifecycleIntegration.lambda$close$1$io-sentry-android-core-AppLifecycleIntegration(AppLifecycleIntegration.java:123)
at io.sentry.android.core.AppLifecycleIntegration$$ExternalSyntheticLambda0.run(Unknown Source:2)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7870)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

also have this log

```
Native Integrations '[io.sentry.UncaughtExceptionHandlerIntegration@714bce2, io.sentry.ShutdownHookIntegration@e2d7873]'
```

**Comment by krystofwoldrich** [comment]
Hi @Qdafengzi,
thank you for the message, 

what version of `@sentry/react-native@v4` are you using exactly?

If you are using [SAGP](https://docs.sentry.io/platforms/android/configuration/gradle/), what version are you using?

Would you be able to provide steps to reproduce the issue or a minimal reproducible example?

**Comment by Qdafengzi** [comment]
> Hi @Qdafengzi, thank you for the message,
> 
> what version of `@sentry/react-native@v4` are you using exactly?
> 
> If you are using [SAGP](https://docs.sentry.io/platforms/android/configuration/gradle/), what version are you using?
> 
> Would you be able to provide steps to reproduce the issue or a minimal reproducible example?


Sorry for the late reply. I have been on vacation all along。

   "@sentry/react-native": "^5.22.0"  I have change this exactly  version 
   
   android project 
   classpath("io.sentry:sentry-android-gradle-plugin:4.5.0")
   
Maybe I need to observe and see if there is still this issue

**Comment by krystofwoldrich** [comment]
@Qdafengzi No worries, thank you for the update.
