### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lio/sentry/event/EventBuilder

### ISSUE THREAD

**Issue by mahmoudfelfel** [getsentry/sentry-react-native#419]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.11.1
5.6.0
myapp@0.0.1 /Users/mahmoud.felfel/projects/myapp
├── algoliasearch@3.26.0
├── await-to-js@2.0.1
├── babel-plugin-transform-remove-console@6.9.2
├── get-urls@7.2.0
├── lodash@4.17.4
├── native-base@2.3.4
├── UNMET PEER DEPENDENCY react@16.0.0
├── react-mixin@2.0.2
├── UNMET PEER DEPENDENCY react-native@0.51.0
├── react-native-bottomsheet@1.8.1
├── react-native-button@2.1.0
├── react-native-deprecated-custom-components@0.1.1
├── react-native-dropdownalert@3.4.0
├── react-native-fast-image@4.0.14 (github:DylanVann/react-native-fast-image#e5838165b6f6e56af534cb6f59dca81cd87dfcdf)
├── react-native-fbsdk@0.7.0
├── react-native-firebase@4.0.4
├── react-native-fs@2.9.12
├── react-native-google-signin@0.11.0 (github:njt1982/react-native-google-signin#1c99bcf05c77f54e2582fe25fdae93bfcef23c7f)
├── react-native-indicators@0.13.0
├── react-native-intercom@10.2.0
├── react-native-linear-gradient@2.4.0
├── react-native-masonry-layout@1.0.5
├── react-native-modalbox@1.4.2
├── react-native-offline@3.7.4
├── react-native-router-flux@4.0.0-beta.24
├── react-native-sentry@0.37.1
├── react-native-share-extension@1.2.1 (git+https://github.com/birkir/react-native-share-extension.git#123d0e4e9745f845e6d8a1f9273db16e4bddf957)
├── react-native-size-matters@0.1.0
├── react-native-smart-splash-screen@2.3.5
├── react-native-smart-toast@1.1.1
├── react-native-splash-screen@3.0.7 (git+https://github.com/crazycodeboy/react-native-splash-screen.git#5f30607de6882cd8f57bf29afa89d2ecb994e6d9)
├── react-native-svg@6.3.1
├── react-native-swiper@1.5.13
├── react-native-swiss-knife@0.0.5
├── react-native-track-player@0.2.4
├── react-native-tts@1.5.0
├── react-native-twitter-signin@1.0.2
├── react-native-typography@1.3.0
├── react-native-vector-icons@4.4.2
├── react-redux@5.0.6
├── react-timer-mixin@0.13.3
├── recyclerlistview@1.4.0-beta.3
├── redux@3.7.2
├── redux-persist@5.4.0
├── redux-thunk@2.2.0
└── url@0.11.0
```

Config:

```
Sentry.config('https://...@sentry.io/...').install()
```

---
I have following issue:

```
06-06 14:04:09.776 4934-5009/com.myapp E/ReactNativeJS: Java exception in 'NativeModules'
    
    java.lang.NoClassDefFoundError: Failed resolution of: Lio/sentry/event/EventBuilder;
06-06 14:04:09.780 4934-5009/com.myapp E/ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)
    
    --------- beginning of crash
06-06 14:04:09.784 4934-5010/com.myapp E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.myapp, PID: 4934
    com.facebook.react.common.JavascriptException: Java exception in 'NativeModules'
    
    java.lang.NoClassDefFoundError: Failed resolution of: Lio/sentry/event/EventBuilder;, stack:
    java.lang.reflect.Method.getParameterTypes@179
    java.lang.Class.getDeclaredMethods@1881
    com.facebook.react.bridge.JavaModuleWrapper.findMethods@90
    com.facebook.react.bridge.JavaModuleWrapper.getMethodDescriptors@120
    android.os.Handler.handleCallback@790
    android.os.Handler.dispatchMessage@99
    com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage@31
```

I get the above Error and the app crashes only when I make a release apk. during debugging, the app works fine.

**Comment by rt012** [comment]
I encountered the same problem. Do you have news? @mahmoudfelfel

**Comment by bonbonez** [comment]
Same for me, can't figure out how to fix this. @mahmoudfelfel @rt012 do you guys have any updates?

**Comment by anandwahed** [comment]
@HazAT  facing the same error after updating the library to the latest version `0.40.3`

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.

**Comment by technoplato** [comment]
@HazAT Just upgraded to and ran into another NoClassDefError related to `OkHttpClient` - do you want me to open a new issue since it's a different class that's not found?

Stacktrace:

```
2024-04-12 15:53:50.941  8725-8824  AndroidRuntime          com.lively.app.pre                   E  FATAL EXCEPTION: OkHttp Dispatcher
                                                                                                    Process: com.lively.app.pre, PID: 8725
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Lio/sentry/IntegrationName;
                                                                                                    	at okhttp3.OkHttpClient.newCall(OkHttpClient.kt:268)
                                                                                                    	at com.facebook.react.devsupport.PackagerStatusCheck.run(PackagerStatusCheck.java:50)
                                                                                                    	at com.facebook.react.devsupport.DevServerHelper.isPackagerRunning(DevServerHelper.java:483)
                                                                                                    	at com.facebook.react.devsupport.DevSupportManagerBase$19.run(DevSupportManagerBase.java:895)
                                                                                                    	at com.facebook.react.devsupport.DevSupportManagerBase.isPackagerRunning(DevSupportManagerBase.java:901)
                                                                                                    	at com.facebook.react.ReactInstanceManager.recreateReactContextInBackgroundInner(ReactInstanceManager.java:454)
                                                                                                    	at com.facebook.react.ReactInstanceManager.createReactContextInBackground(ReactInstanceManager.java:420)
                                                                                                    	at com.facebook.react.ReactRootView.startReactApplication(ReactRootView.java:500)
                                                                                                    	at com.facebook.react.ReactRootView.startReactApplication(ReactRootView.java:469)
                                                                                                    	at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:120)
                                                                                                    	at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:114)
                                                                                                    	at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:109)
                                                                                                    	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:46)
                                                                                                    	at com.lively.app.MainActivity.onCreate(MainActivity.kt:40)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8051)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8031)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "io.sentry.IntegrationName" on path: DexPathList[[zip file "/data/app/~~jlX6IutedZAmRB8RH4Ddyg==/com.lively.app.pre-v7OLeSBVQ95A7L2I2MR0vg==/base.apk"],nativeLibraryDirectories=[/data/app/~~jlX6IutedZAmRB8RH4Ddyg==/com.lively.app.pre-v7OLeSBVQ95A7L2I2MR0vg==/lib/arm64, /data/app/~~jlX6IutedZAmRB8RH4Ddyg==/com.lively.app.pre-v7OLeSBVQ95A7L2I2MR0vg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:218)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at okhttp3.OkHttpClient.newCall(OkHttpClient.kt:268) 
                                                                                                    	at com.facebook.react.devsupport.PackagerStatusCheck.run(PackagerStatusCheck.java:50) 
                                                                                                    	at com.facebook.react.devsupport.DevServerHelper.isPackagerRunning(DevServerHelper.java:483) 
                                                                                                    	at com.facebook.react.devsupport.DevSupportManagerBase$19.run(DevSupportManagerBase.java:895) 
                                                                                                    	at com.facebook.react.devsupport.DevSupportManagerBase.isPackagerRunning(DevSupportManagerBase.java:901) 
                                                                                                    	at com.facebook.react.ReactInstanceManager.recreateReactContextInBackgroundInner(ReactInstanceManager.java:454) 
                                                                                                    	at com.facebook.react.ReactInstanceManager.createReactContextInBackground(ReactInstanceManager.java:420) 
                                                                                                    	at com.facebook.react.ReactRootView.startReactApplication(ReactRootView.java:500) 
                                                                                                    	at com.facebook.react.ReactRootView.startReactApplication(ReactRootView.java:469) 
                                                                                                    	at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:120) 
                                                                                                    	at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:114) 
                                                                                                    	at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:109) 
                                                                                                    	at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:46) 
                                                                                                    	at com.lively.app.MainActivity.onCreate(MainActivity.kt:40) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8051) 
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8031) 
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329) 
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608) 
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7839) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```
