### ISSUE TITLE
Error events are not recorded in Sentry dashboard

### ISSUE THREAD

**Issue by jenipharachel** [getsentry/sentry-react-native#4221]
### What React Native libraries do you use?

React Navigation

### Are you using sentry.io or on-premise?

on-premise (Self-Hosted)

### @sentry/react-native SDK Version

5.33.1

### How does your development environment look like?

info
OS: MacOS
Node: v16.9.0
Yarn: 1.22.19
react: "17.0.2"
react-native: "0.67.2"
hermesEnabled: false
newArchEnabled: false

### Sentry.init()

    Sentry.init({
      dsn: "",
      // Set tracesSampleRate to 1.0 to capture 100% of transactions for performance monitoring.
      // We recommend adjusting this value in production.
      debug: true,
      tracesSampleRate: 1.0,
      release: release + '@' + VersionNumber.appVersion + '+' + VersionNumber.buildVersion,
    })

### Steps to Reproduce

1. Built the app in iOS and android.
2. Crashed the app with "throw new Error("My first Sentry error!");" or "Sentry.nativeCrash();"
3. Crash occured but was not recorded in Sentry Dashboard. Production bugs are also not recorded in the Sentry Dashboard.

### Expected Result

Crashes to be recorded in Sentry

### Actual Result

 Crash occured but was not recorded in Sentry Dashboard. Production bugs are also not recorded in the Sentry Dashboard.

**Comment by rwachtler** [comment]
Thank you for reaching out here @jenipharachel ! Couple of points to help you resolve this issue faster:

- Could you please provide the Sentry log output from your console 
- Is it a "new" setup or did it just stop capturing errors after an update etc. 
  - if you've encountered this in an existing setup (Sentry worked before), do you recall what your last action was, before it stopped working

**Comment by jenipharachel** [comment]
@rwachtler 
- I'm not sure how I could provide you the Sentry logs. I don't see them in my console.
- It was already setup previously by another developer who is no longer with us, not sure when it stopped working cause I can't see any issues from before August. We only noticed it was not working when there were crashes reported by our users which were not caught in Sentry.
- I redid the setup using the command `npx @sentry/wizard@latest -i reactNative` but still it is not working.

**Comment by lucas-zimerman** [comment]
Hi @jenipharachel, which version of self-hosted are you using? And could you by any chance check if the error is recorded if you use sentry.io (on a free tier)?

**Comment by jenipharachel** [comment]
@lucas-zimerman I'm using "@sentry/react-native": "^5.33.1". And yes, I checked with the DSN from a free tier project and it is not getting logged there as well.

**Comment by jenipharachel** [comment]
@krystofwoldrich I added the below code for testing. DefaultButton is a component already used in our code.  It occurs in both. I have not tested in a real device but We had been receiving multiple crash reports from users but none are logged in the Sentry dashboard.

```
            <DefaultButton
              btnText="Try Me!"
              onPress={() => Sentry.captureException(new Error('My first Sentry error!'))}
            />
```

When I tested in iOS simulator, I saw the below logs when I clicked on the button

```
LOG  Sentry Logger [log]: [TouchEvents] Touch event within element: View
 WARN  Sentry Logger [warn]: Unable to symbolicate stack trace: stackWithoutPoppedFrames.filter is not a function. (In 'stackWithoutPoppedFrames.filter(function (frame) {
                return frame.file && frame.file.match(INTERNAL_CALLSITES_REGEX) === null;
              })', 'stackWithoutPoppedFrames.filter' is undefined)
```

In Android emulator, When I clicked on the button I received the a long list of logs, I have added a part of the logs below

```
2024-11-06 17:55:27.374  8359-8678  Sentry                  com.webpartners.leonardo             W  Cache folder if full (respecting maxSize). Rotating files
2024-11-06 17:55:27.376  8359-8678  Sentry                  com.webpartners.leonardo             W  Current envelope doesn't exist.
2024-11-06 17:55:27.376  8359-8678  Sentry                  com.webpartners.leonardo             D  Adding Envelope to offline storage: /data/user/0/com.webpartners.leonardo/cache/sentry/cdb5ba61ee01856db6fc720edfffaa8b6326855b/a4e999ce-ebb4-4fc4-88ae-264968711353.envelope
2024-11-06 17:55:27.377  8359-8678  Sentry                  com.webpartners.leonardo             D  Serializing object: {
                                                                                                    	"sid": "6ec300ff-febf-4d8f-b5c5-2ff6ab7df5e2",
                                                                                                    	"did": "e6c4dd76-a98c-4e11-83ef-025f5797ffec",
                                                                                                    	"started": "2024-11-06T12:22:24.465Z",
                                                                                                    	"status": "exited",
                                                                                                    	"seq": 1730895927373,
                                                                                                    	"errors": 1,
                                                                                                    	"duration": 182.908,
                                                                                                    	"timestamp": "2024-11-06T12:25:27.373Z",
                                                                                                    	"attrs": {
                                                                                                    		"release": "com.webpartners.leonardo@1+100001",
                                                                                                    		"environment": "development"
                                                                                                    	}
                                                                                                    }
2024-11-06 17:55:27.379  8359-8678  Sentry                  com.webpartners.leonardo             D  Attaching client report to envelope.
2024-11-06 17:55:27.430  8359-8678  TrafficStats            com.webpartners.leonardo             D  tagSocket(108) with statsTag=0xffffffff, statsUid=-1
2024-11-06 17:55:27.814  8359-8678  Sentry                  com.webpartners.leonardo             D  Serializing object: {
                                                                                                    	"timestamp": "2024-11-06T12:25:27.379Z",
                                                                                                    	"discarded_events": [
                                                                                                    		{
                                                                                                    			"reason": "cache_overflow",
                                                                                                    			"category": "session",
                                                                                                    			"quantity": 1
                                                                                                    		}
                                                                                                    	]
                                                                                                    }
2024-11-06 17:55:28.189  8359-8678  Sentry                  com.webpartners.leonardo             D  Request failed, API returned 301
2024-11-06 17:55:28.190  8359-8678  Sentry                  com.webpartners.leonardo             E  Envelope submission failed
                                                                                                    java.lang.NullPointerException
                                                                                                    	at java.io.Reader.<init>(Reader.java:167)
                                                                                                    	at java.io.InputStreamReader.<init>(InputStreamReader.java:112)
                                                                                                    	at io.sentry.transport.HttpConnection.getErrorMessageFromStream(HttpConnection.java:248)
                                                                                                    	at io.sentry.transport.HttpConnection.readAndLog(HttpConnection.java:184)
                                                                                                    	at io.sentry.transport.HttpConnection.send(HttpConnection.java:163)
                                                                                                    	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.flush(AsyncHttpTransport.java:298)
                                                                                                    	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.run(AsyncHttpTransport.java:243)
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2024-11-06 17:55:28.194  8359-8678  Sentry                  com.webpartners.leonardo             W  Cache folder if full (respecting maxSize). Rotating files
2024-11-06 17:55:28.202  8359-8678  Sentry                  com.webpartners.leonardo             D  Session d55ae09d-9910-45b2-8db1-9a5eb7fcca46 has 2 times the init flag.
2024-11-06 17:55:28.202  8359-8678  Sentry                  com.webpartners.leonardo             D  Serializing object: {
                                                                                                    	"sid": "db737525-f255-4507-b5be-e2f604a261b9",
                                                                                                    	"did": "e6c4dd76-a98c-4e11-83ef-025f5797ffec",
                                                                                                    	"init": true,
                                                                                                    	"started": "2024-11-06T12:25:27.373Z",
                                                                                                    	"status": "ok",
                                                                                                    	"errors": 0,
                                                                                                    	"timestamp": "2024-11-06T12:25:27.373Z",
                                                                                                    	"attrs": {
                                                                                                    		"release": "com.webpartners.leonardo@1+100001",
                                                                                                    		"environment": "development"
                                                                                                    	}
                                                                                                    }
2024-11-06 17:55:28.203  8359-8678  Sentry                  com.webpartners.leonardo             D  Serializing object: {
                                                                                                    	"sid": "db737525-f255-4507-b5be-e2f604a261b9",
                                                                                                    	"did": "e6c4dd76-a98c-4e11-83ef-025f5797ffec",
                                                                                                    	"init": true,
                                                                                                    	"started": "2024-11-06T12:25:27.373Z",
                                                                                                    	"status": "ok",
                                                                                                    	"errors": 0,
                                                                                                    	"timestamp": "2024-11-06T12:25:27.373Z",
                                                                                                    	"attrs": {
                                                                                                    		"release": "com.webpartners.leonardo@1+100001",
                                                                                                    		"environment": "development"
                                                                                                    	}
                                                                                                    }
2024-11-06 17:55:28.203  8359-8678  Sentry                  com.webpartners.leonardo             D  Adding Envelope to offline storage: /data/user/0/com.webpartners.leonardo/cache/sentry/cdb5ba61ee01856db6fc720edfffaa8b6326855b/f0bbb6df-7fe9-4737-b816-67c48f52359e.envelope
2024-11-06 17:55:28.205  8359-8678  Sentry                  com.webpartners.leonardo             D  Attaching client report to envelope.
2024-11-06 17:55:28.205  8359-8678  TrafficStats            com.webpartners.leonardo             D  tagSocket(108) with statsTag=0xffffffff, statsUid=-1
2024-11-06 17:55:28.499  8359-8678  Sentry                  com.webpartners.leonardo             D  Serializing object: {
                                                                                                    	"timestamp": "2024-11-06T12:25:28.204Z",
                                                                                                    	"discarded_events": [
                                                                                                    		{
                                                                                                    			"reason": "cache_overflow",
                                                                                                    			"category": "session",
                                                                                                    			"quantity": 1
                                                                                                    		}
                                                                                                    	]
                                                                                                    }
2024-11-06 17:55:28.784  8359-8678  Sentry                  com.webpartners.leonardo             D  Request failed, API returned 301
2024-11-06 17:55:28.794  8359-8678  Sentry                  com.webpartners.leonardo             E  Envelope submission failed
                                                                                                    java.lang.NullPointerException
                                                                                                    	at java.io.Reader.<init>(Reader.java:167)
                                                                                                    	at java.io.InputStreamReader.<init>(InputStreamReader.java:112)
                                                                                                    	at io.sentry.transport.HttpConnection.getErrorMessageFromStream(HttpConnection.java:248)
                                                                                                    	at io.sentry.transport.HttpConnection.readAndLog(HttpConnection.java:184)
                                                                                                    	at io.sentry.transport.HttpConnection.send(HttpConnection.java:163)
                                                                                                    	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.flush(AsyncHttpTransport.java:298)
                                                                                                    	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.run(AsyncHttpTransport.java:243)
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
2024-11-06 17:55:28.796  8359-8678  Sentry                  com.webpartners.leonardo             W  Cache folder if full (respecting maxSize). Rotating files
2024-11-06 17:55:28.800  8359-8678  Sentry                  com.webpartners.leonardo             D  Adding Envelope to offline storage: /data/user/0/com.webpartners.leonardo/cache/sentry/cdb5ba61ee01856db6fc720edfffaa8b6326855b/6c44555d-aeed-46dc-b890-f236c180f10d.envelope
2024-11-06 17:55:28.801  8359-8678  Sentry                  com.webpartners.leonardo             D  Serializing object: {
                                                                                                    	"sid": "6ec300ff-febf-4d8f-b5c5-2ff6ab7df5e2",
                                                                                                    	"did": "e6c4dd76-a98c-4e11-83ef-025f5797ffec",
                                                                                                    	"started": "2024-11-06T12:22:24.465Z",
                                                                                                    	"status": "exited",
                                                                                                    	"seq": 1730895927373,
                                                                                                    	"errors": 1,
                                                                                                    	"duration": 182.908,
                                                                                                    	"timestamp": "2024-11-06T12:25:27.373Z",
                                                                                                    	"attrs": {
                                                                                                    		"release": "com.webpartners.leonardo@1+100001",
                                                                                                    		"environment": "development"
                                                                                                    	}
                                                                                                    }
2024-11-06 17:55:28.803  8359-8678  Sentry                  com.webpartners.leonardo             D  Attaching client report to envelope.
2024-11-06 17:55:28.805  8359-8678  TrafficStats            com.webpartners.leonardo             D  tagSocket(108) with statsTag=0xffffffff, statsUid=-1
2024-11-06 17:55:29.116  8359-8678  Sentry                  com.webpartners.leonardo             D  Serializing object: {
                                                                                                    	"timestamp": "2024-11-06T12:25:28.802Z",
                                                                                                    	"discarded_events": [
                                                                                                    		{
                                                                                                    			"reason": "cache_overflow",
                                                                                                    			"category": "error",
                                                                                                    			"quantity": 1
                                                                                                    		},
                                                                                                    		{
                                                                                                    			"reason": "cache_overflow",
                                                                                                    			"category": "session",
                                                                                                    			"quantity": 1
                                                                                                    		}
                                                                                                    	]
                                                                                                    }
2024-11-06 17:55:29.425  8359-8678  Sentry                  com.webpartners.leonardo             D  Request failed, API returned 301
2024-11-06 17:55:29.428  8359-8678  Sentry                  com.webpartners.leonardo             E  Envelope submission failed
                                                                                                    java.lang.NullPointerException
                                                                                                    	at java.io.Reader.<init>(Reader.java:167)
                                                                                                    	at java.io.InputStreamReader.<init>(InputStreamReader.java:112)
                                                                                                    	at io.sentry.transport.HttpConnection.getErrorMessageFromStream(HttpConnection.java:248)
                                                                                                    	at io.sentry.transport.HttpConnection.readAndLog(HttpConnection.java:184)
                                                                                                    	at io.sentry.transport.HttpConnection.send(HttpConnection.java:163)
                                                                                                    	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.flush(AsyncHttpTransport.java:298)
                                                                                                    	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.run(AsyncHttpTransport.java:243)
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)


```

**Comment by krystofwoldrich** [comment]
@jenipharachel Thank you for the logs.

The envelopes are not being uploaded to Sentry due to Permanent Move 301 return code.

```
2024-11-06 17:55:28.784  8359-8678  Sentry                             D  Request failed, API returned 301
2024-11-06 17:55:28.794  8359-8678  Sentry                               E  Envelope submission failed
```

Are these logs from Sentry.io DSN or from the Self Hosted?

**Comment by jenipharachel** [comment]
@krystofwoldrich The above logs are from the self-hosted one. Do you want the logs from Sentry.io DSN?

**Comment by krystofwoldrich** [comment]
Hi @jenipharachel, 
my knowledge of self-hosted is limited, but if you share the server logs here, my colleagues can help you out.

**Comment by jenipharachel** [comment]
Hi @krystofwoldrich 
Sorry for the delay. Here's the logcat logs from Android Studio

[Untitled.txt](https://github.com/user-attachments/files/18473576/Untitled.txt)

**Comment by Is-fff** [comment]
> ### 您使用哪些 React Native 库？
> React 导航
> 
> ### 您使用的是 sentry.io 还是本地部署？
> 本地 （自托管）
> 
> ### @sentry/react-native SDK 版本
> 5.33.1
> 
> ### 您的开发环境是什么样的？
> info OS： MacOS 节点： v16.9.0 Yarn： 1.22.19 react： “17.0.2” react-native： “0.67.2” hermesEnabled： false newArchEnabled： false
> 
> ### Sentry.init（）
> ```
> Sentry.init({
>   dsn: "",
>   // Set tracesSampleRate to 1.0 to capture 100% of transactions for performance monitoring.
>   // We recommend adjusting this value in production.
>   debug: true,
>   tracesSampleRate: 1.0,
>   release: release + '@' + VersionNumber.appVersion + '+' + VersionNumber.buildVersion,
> })
> ```
> 
> ### 重现步骤
> 1. 在 iOS 和 Android 中构建应用程序。
> 2. 导致应用程序崩溃，并显示 “throw new Error（”My first Sentry error！“）;” 或 “Sentry.nativeCrash（）;”
> 3. 发生崩溃，但未记录在 Sentry Dashboard 中。生产错误也不会记录在 Sentry 仪表板中。
> 
> ### 预期结果
> 在 Sentry 中记录崩溃
> 
> ### 实际结果
> 发生崩溃，但未记录在 Sentry Dashboard 中。生产错误也不会记录在 Sentry 仪表板中。



> [@rwachtler](https://github.com/rwachtler)
> 
> * I'm not sure how I could provide you the Sentry logs. I don't see them in my console.
> * It was already setup previously by another developer who is no longer with us, not sure when it stopped working cause I can't see any issues from before August. We only noticed it was not working when there were crashes reported by our users which were not caught in Sentry.
> * I redid the setup using the command `npx @sentry/wizard@latest -i reactNative` but still it is not working.

same problem.What should i do to make it working?
