### ISSUE TITLE
Couldn't find key stacktrace in dynamic 

### ISSUE THREAD

**Issue by kyo504** [getsentry/sentry-react-native#438]
OS:
- [ ]  Windows
- [ ]  MacOS
- [x]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

Output of `node -v && yarn -v && yarn list --prod --depth=0`

```
v8.11.3
1.7.0
yarn list v1.7.0
warning Resolution field "uglify-js@3.1.9" is incompatible with requested version "uglify-js@^2.6"
├─ @actra-development-oss/redux-persist-transform-filter-immutable@0.2.1
├─ @sentry/cli@1.32.3
├─ @sentry/wizard@0.9.7
├─ abbrev@1.1.1
├─ absolute-path@0.0.0
├─ accepts@1.2.13
├─ adm-zip@0.4.11
├─ agent-base@4.2.0
├─ ajv@5.5.2
├─ ansi-colors@1.1.0
├─ ansi-cyan@0.1.1
├─ ansi-escapes@3.1.0
├─ ansi-gray@0.1.1
├─ ansi-red@0.1.1
├─ ansi-regex@2.1.1
├─ ansi-styles@2.2.1
├─ ansi-wrap@0.1.0
├─ ansi@0.3.1
├─ anymatch@2.0.0
├─ aproba@1.2.0
├─ arch@2.1.1
├─ are-we-there-yet@1.1.5
├─ arr-diff@4.0.0
├─ arr-flatten@1.1.0
├─ arr-union@3.1.0
├─ array-filter@0.0.1
├─ array-map@0.0.0
├─ array-reduce@0.0.0
├─ array-slice@0.2.3
├─ array-unique@0.3.2
├─ art@0.10.2
├─ asap@2.0.6
├─ asn1@0.2.3
├─ assert-plus@1.0.0
├─ assign-symbols@1.0.0
├─ async@2.6.1
├─ asynckit@0.4.0
├─ atob@2.1.1
├─ aws-sign2@0.7.0
├─ aws4@1.7.0
├─ babel-code-frame@6.26.0
├─ babel-core@6.26.3
├─ babel-generator@6.26.1
├─ babel-helper-builder-binary-assignment-operator-visitor@6.24.1
├─ babel-helper-builder-react-jsx@6.26.0
├─ babel-helper-call-delegate@6.24.1
├─ babel-helper-define-map@6.26.0
├─ babel-helper-explode-assignable-expression@6.24.1
├─ babel-helper-function-name@6.24.1
├─ babel-helper-get-function-arity@6.24.1
├─ babel-helper-hoist-variables@6.24.1
├─ babel-helper-optimise-call-expression@6.24.1
├─ babel-helper-regex@6.26.0
├─ babel-helper-remap-async-to-generator@6.24.1
├─ babel-helper-replace-supers@6.24.1
├─ babel-helpers@6.24.1
├─ babel-messages@6.23.0
├─ babel-plugin-check-es2015-constants@6.22.0
├─ babel-plugin-external-helpers@6.22.0
├─ babel-plugin-react-transform@3.0.0
├─ babel-plugin-syntax-async-functions@6.13.0
├─ babel-plugin-syntax-class-properties@6.13.0
├─ babel-plugin-syntax-dynamic-import@6.18.0
├─ babel-plugin-syntax-exponentiation-operator@6.13.0
├─ babel-plugin-syntax-flow@6.18.0
├─ babel-plugin-syntax-jsx@6.18.0
├─ babel-plugin-syntax-object-rest-spread@6.13.0
├─ babel-plugin-syntax-trailing-function-commas@6.22.0
├─ babel-plugin-transform-async-to-generator@6.16.0
├─ babel-plugin-transform-class-properties@6.24.1
├─ babel-plugin-transform-es2015-arrow-functions@6.22.0
├─ babel-plugin-transform-es2015-block-scoped-functions@6.22.0
├─ babel-plugin-transform-es2015-block-scoping@6.26.0
├─ babel-plugin-transform-es2015-classes@6.24.1
├─ babel-plugin-transform-es2015-computed-properties@6.24.1
├─ babel-plugin-transform-es2015-destructuring@6.23.0
├─ babel-plugin-transform-es2015-for-of@6.23.0
├─ babel-plugin-transform-es2015-function-name@6.24.1
├─ babel-plugin-transform-es2015-literals@6.22.0
├─ babel-plugin-transform-es2015-modules-commonjs@6.26.2
├─ babel-plugin-transform-es2015-object-super@6.24.1
├─ babel-plugin-transform-es2015-parameters@6.24.1
├─ babel-plugin-transform-es2015-shorthand-properties@6.24.1
├─ babel-plugin-transform-es2015-spread@6.22.0
├─ babel-plugin-transform-es2015-sticky-regex@6.24.1
├─ babel-plugin-transform-es2015-template-literals@6.22.0
├─ babel-plugin-transform-es2015-unicode-regex@6.24.1
├─ babel-plugin-transform-es3-member-expression-literals@6.22.0
├─ babel-plugin-transform-es3-property-literals@6.22.0
├─ babel-plugin-transform-exponentiation-operator@6.24.1
├─ babel-plugin-transform-flow-strip-types@6.22.0
├─ babel-plugin-transform-object-assign@6.22.0
├─ babel-plugin-transform-object-rest-spread@6.26.0
├─ babel-plugin-transform-react-display-name@6.25.0
├─ babel-plugin-transform-react-jsx-source@6.22.0
├─ babel-plugin-transform-react-jsx@6.24.1
├─ babel-plugin-transform-regenerator@6.26.0
├─ babel-plugin-transform-strict-mode@6.24.1
├─ babel-polyfill@6.23.0
├─ babel-preset-es2015-node@6.1.1
├─ babel-preset-fbjs@2.1.4
├─ babel-preset-react-native@4.0.0
├─ babel-register@6.26.0
├─ babel-runtime@6.26.0
├─ babel-template@6.26.0
├─ babel-traverse@6.26.0
├─ babel-types@6.26.0
├─ babylon@6.18.0
├─ balanced-match@1.0.0
├─ base-64@0.1.0
├─ base@0.11.2
├─ base64-js@0.0.8
├─ base64-url@1.2.1
├─ basic-auth-connect@1.0.0
├─ basic-auth@1.0.4
├─ batch@0.5.3
├─ bcrypt-pbkdf@1.0.1
├─ big-integer@1.6.31
├─ body-parser@1.13.3
├─ bplist-creator@0.0.7
├─ bplist-parser@0.1.1
├─ brace-expansion@1.1.11
├─ braces@2.3.2
├─ bser@2.0.0
├─ buffer-from@1.1.0
├─ builtin-modules@1.1.1
├─ bytes@2.1.0
├─ cache-base@1.0.1
├─ camelcase@4.1.0
├─ capture-exit@1.2.0
├─ caseless@0.12.0
├─ chalk@1.1.3
├─ chardet@0.4.2
├─ chownr@1.0.1
├─ class-utils@0.3.6
├─ cli-cursor@2.1.0
├─ cli-width@2.2.0
├─ clipboardy@1.2.3
├─ cliui@3.2.0
├─ co@4.6.0
├─ code-point-at@1.1.0
├─ collection-visit@1.0.0
├─ color-convert@1.9.1
├─ color-name@1.1.3
├─ color-string@1.5.2
├─ color-support@1.1.3
├─ color@2.0.1
├─ combined-stream@1.0.6
├─ commander@2.15.1
├─ component-emitter@1.2.1
├─ compressible@2.0.14
├─ compression@1.5.2
├─ concat-map@0.0.1
├─ concat-stream@1.6.2
├─ connect-timeout@1.6.2
├─ connect@2.30.2
├─ console-control-strings@1.1.0
├─ constant-mirror@1.1.1
├─ content-type@1.0.4
├─ convert-source-map@1.5.1
├─ cookie-parser@1.3.5
├─ cookie-signature@1.0.6
├─ cookie@0.1.3
├─ copy-descriptor@0.1.1
├─ core-js@2.5.7
├─ core-util-is@1.0.2
├─ crc@3.3.0
├─ create-react-class@15.6.3
├─ cross-spawn@5.1.0
├─ csrf@3.0.6
├─ csurf@1.8.3
├─ dashdash@1.14.1
├─ debug@2.6.9
├─ decamelize@1.2.0
├─ decode-uri-component@0.2.0
├─ decompress-response@3.3.0
├─ dedent@0.6.0
├─ deep-extend@0.6.0
├─ define-property@0.2.5
├─ delayed-stream@1.0.0
├─ delegates@1.0.0
├─ denodeify@1.2.1
├─ depd@1.0.1
├─ destroy@1.0.4
├─ detect-indent@4.0.0
├─ detect-libc@1.0.3
├─ detect-newline@2.1.0
├─ dom-walk@0.1.1
├─ duplexer3@0.1.4
├─ ecc-jsbn@0.1.1
├─ ee-first@1.1.1
├─ encodeurl@1.0.2
├─ encoding@0.1.12
├─ end-of-stream@1.4.1
├─ envinfo@3.11.1
├─ error-ex@1.3.2
├─ errorhandler@1.4.3
├─ es6-promise@4.2.4
├─ es6-promisify@5.0.0
├─ escape-html@1.0.3
├─ escape-string-regexp@1.0.5
├─ esutils@2.0.2
├─ etag@1.7.0
├─ event-target-shim@1.1.1
├─ eventemitter3@2.0.3
├─ exec-sh@0.2.1
├─ execa@0.7.0
├─ expand-brackets@2.1.4
├─ expand-range@1.8.2
├─ express-session@1.11.3
├─ extend-shallow@2.0.1
├─ extend@3.0.1
├─ external-editor@2.2.0
├─ extglob@2.0.4
├─ extsprintf@1.3.0
├─ fancy-log@1.3.2
├─ fast-deep-equal@1.1.0
├─ fast-json-stable-stringify@2.0.0
├─ fastfall@1.5.1
├─ fb-watchman@2.0.0
├─ fbjs-scripts@0.8.3
├─ fbjs@0.8.17
├─ figures@2.0.0
├─ filename-regex@2.0.1
├─ fill-range@4.0.0
├─ finalhandler@0.4.0
├─ find-up@2.1.0
├─ for-in@1.0.2
├─ for-own@0.1.5
├─ forever-agent@0.6.1
├─ form-data@2.3.2
├─ fragment-cache@0.2.1
├─ fresh@0.3.0
├─ fs-extra@1.0.0
├─ fs-minipass@1.2.5
├─ fs.realpath@1.0.0
├─ fsevents@1.2.4
├─ gauge@1.2.7
├─ get-caller-file@1.0.2
├─ get-stream@3.0.0
├─ get-value@2.0.6
├─ getpass@0.1.7
├─ glob-base@0.3.0
├─ glob-parent@2.0.0
├─ glob@7.1.2
├─ global@4.3.2
├─ globals@9.18.0
├─ got@7.1.0
├─ graceful-fs@4.1.11
├─ growly@1.3.0
├─ har-schema@2.0.0
├─ har-validator@5.0.3
├─ has-ansi@2.0.0
├─ has-flag@3.0.0
├─ has-symbol-support-x@1.4.2
├─ has-to-string-tag-x@1.4.1
├─ has-unicode@2.0.1
├─ has-value@1.0.0
├─ has-values@1.0.0
├─ hoist-non-react-statics@2.5.5
├─ home-or-tmp@2.0.0
├─ hosted-git-info@2.6.0
├─ http-errors@1.3.1
├─ http-signature@1.2.0
├─ https-proxy-agent@2.2.1
├─ iconv-lite@0.4.23
├─ ignore-walk@3.0.1
├─ image-size@0.6.3
├─ immutable@3.8.2
├─ imurmurhash@0.1.4
├─ inflight@1.0.6
├─ inherits@2.0.3
├─ ini@1.3.5
├─ inquirer@3.3.0
├─ invariant@2.2.4
├─ invert-kv@1.0.0
├─ is-accessor-descriptor@1.0.0
├─ is-arrayish@0.3.2
├─ is-buffer@1.1.6
├─ is-builtin-module@1.0.0
├─ is-data-descriptor@1.0.0
├─ is-descriptor@1.0.2
├─ is-dotfile@1.0.3
├─ is-equal-shallow@0.1.3
├─ is-extendable@0.1.1
├─ is-extglob@1.0.0
├─ is-finite@1.0.2
├─ is-fullwidth-code-point@2.0.0
├─ is-glob@2.0.1
├─ is-number@3.0.0
├─ is-object@1.0.1
├─ is-odd@2.0.0
├─ is-plain-obj@1.1.0
├─ is-plain-object@2.0.4
├─ is-posix-bracket@0.1.1
├─ is-primitive@2.0.0
├─ is-promise@2.1.0
├─ is-retry-allowed@1.1.0
├─ is-stream@1.1.0
├─ is-typedarray@1.0.0
├─ is-windows@1.0.2
├─ isarray@1.0.0
├─ isexe@2.0.0
├─ isobject@3.0.1
├─ isomorphic-fetch@2.2.1
├─ isstream@0.1.2
├─ isurl@1.0.0
├─ jest-docblock@22.1.0
├─ jest-haste-map@22.1.0
├─ jest-worker@22.1.0
├─ js-tokens@3.0.2
├─ jsbn@0.1.1
├─ jsesc@1.3.0
├─ json-schema-traverse@0.3.1
├─ json-schema@0.2.3
├─ json-stable-stringify@1.0.1
├─ json-stringify-safe@5.0.1
├─ json5@0.4.0
├─ jsonfile@2.4.0
├─ jsonify@0.0.0
├─ jsprim@1.4.1
├─ keymirror@0.1.1
├─ kind-of@3.2.2
├─ klaw@1.3.1
├─ lcid@1.0.0
├─ left-pad@1.3.0
├─ load-json-file@2.0.0
├─ locate-path@2.0.0
├─ lodash-es@4.17.10
├─ lodash.forin@4.4.0
├─ lodash.get@4.4.2
├─ lodash.includes@4.3.0
├─ lodash.isempty@4.4.0
├─ lodash.isobject@3.0.2
├─ lodash.isstring@4.0.1
├─ lodash.isundefined@3.0.1
├─ lodash.pad@4.5.1
├─ lodash.padend@4.6.1
├─ lodash.padstart@4.6.1
├─ lodash.pickby@4.6.0
├─ lodash.set@4.3.2
├─ lodash.throttle@4.1.1
├─ lodash.unset@4.5.2
├─ lodash@4.17.4
├─ loose-envify@1.3.1
├─ lottie-ios@2.5.0
├─ lottie-react-native@2.5.0
├─ lowercase-keys@1.0.1
├─ lru-cache@4.1.3
├─ macos-release@1.1.0
├─ makeerror@1.0.11
├─ map-cache@0.2.2
├─ map-visit@1.0.0
├─ math-random@1.0.1
├─ media-typer@0.3.0
├─ mem@1.1.0
├─ merge-stream@1.0.1
├─ merge@1.2.0
├─ method-override@2.3.10
├─ methods@1.1.2
├─ metro-core@0.24.7
├─ metro-source-map@0.24.7
├─ metro@0.24.7
├─ micromatch@3.1.10
├─ mime-db@1.33.0
├─ mime-types@2.1.18
├─ mime@1.6.0
├─ mimic-fn@1.2.0
├─ mimic-response@1.0.0
├─ min-document@2.19.0
├─ minimatch@3.0.4
├─ minimist@1.2.0
├─ minipass@2.3.3
├─ minizlib@1.1.0
├─ mixin-deep@1.3.1
├─ mkdirp@0.5.1
├─ moment-duration-format@2.2.2
├─ moment@2.19.2
├─ morgan@1.6.1
├─ ms@0.7.1
├─ multiparty@3.3.2
├─ mute-stream@0.0.7
├─ nan@2.10.0
├─ nanomatch@1.2.9
├─ needle@2.2.1
├─ negotiator@0.5.3
├─ node-fetch@1.7.3
├─ node-int64@0.4.0
├─ node-notifier@5.2.1
├─ node-pre-gyp@0.10.0
├─ node-uuid@1.4.7
├─ nopt@4.0.1
├─ normalize-package-data@2.4.0
├─ normalize-path@2.1.1
├─ npm-bundled@1.0.3
├─ npm-packlist@1.1.10
├─ npm-run-path@2.0.2
├─ npmlog@2.0.4
├─ number-is-nan@1.0.1
├─ numeral@2.0.6
├─ oauth-sign@0.8.2
├─ object-assign@4.1.1
├─ object-copy@0.1.0
├─ object-visit@1.0.1
├─ object.omit@2.0.1
├─ object.pick@1.3.0
├─ on-finished@2.3.0
├─ on-headers@1.0.1
├─ once@1.4.0
├─ onetime@2.0.1
├─ open@0.0.5
├─ opencollective@1.0.3
├─ opn@3.0.3
├─ optimist@0.6.1
├─ options@0.0.6
├─ os-homedir@1.0.2
├─ os-locale@2.1.0
├─ os-name@2.0.1
├─ os-tmpdir@1.0.2
├─ osenv@0.1.5
├─ p-cancelable@0.3.0
├─ p-finally@1.0.0
├─ p-limit@1.3.0
├─ p-locate@2.0.0
├─ p-timeout@1.2.1
├─ p-try@1.0.0
├─ parse-glob@3.0.4
├─ parse-json@2.2.0
├─ parseurl@1.3.2
├─ pascalcase@0.1.1
├─ path-exists@3.0.0
├─ path-is-absolute@1.0.1
├─ path-key@2.0.1
├─ path-type@2.0.0
├─ pause@0.1.0
├─ pegjs@0.10.0
├─ performance-now@2.1.0
├─ pify@2.3.0
├─ pinkie-promise@2.0.1
├─ pinkie@2.0.4
├─ plist@1.2.0
├─ plugin-error@0.1.2
├─ posix-character-classes@0.1.1
├─ postinstall-build@5.0.1
├─ prepend-http@1.0.4
├─ preserve@0.2.0
├─ pretty-format@4.3.1
├─ private@0.1.8
├─ process-nextick-args@2.0.0
├─ process@0.5.2
├─ progress@2.0.0
├─ promise@7.3.1
├─ prop-types@15.6.0
├─ proxy-from-env@1.0.0
├─ pseudomap@1.0.2
├─ pump@1.0.3
├─ punycode@1.4.1
├─ qs@4.0.0
├─ query-string@5.0.1
├─ querystringify@1.0.0
├─ r2@2.0.1
├─ random-bytes@1.0.0
├─ randomatic@3.0.0
├─ range-parser@1.0.3
├─ raven-js@3.26.2
├─ raw-body@2.1.7
├─ rc@1.2.8
├─ react-addons-shallow-compare@15.6.2
├─ react-clone-referenced-element@1.0.1
├─ react-deep-force-update@1.1.1
├─ react-devtools-core@3.0.0
├─ react-native-adjust@4.13.0
├─ react-native-amplitude-helper@0.1.2
├─ react-native-appboy-sdk@1.6.0
├─ react-native-billing@2.6.1
├─ react-native-bottomsheet@1.8.1
├─ react-native-branch@2.3.0
├─ react-native-device-info@0.12.1
├─ react-native-fbsdk@0.7.0
├─ react-native-firebase@4.2.0
├─ react-native-fs@2.10.14
├─ react-native-google-analytics-bridge@5.7.1
├─ react-native-image-picker@0.26.7
├─ react-native-keychain@1.2.1
├─ react-native-linear-gradient@2.4.0
├─ react-native-navigation@1.1.406
├─ react-native-safe-module@1.2.0
├─ react-native-sentry@0.37.1
├─ react-native-snap-carousel@3.6.0
├─ react-native-sqlite-storage@3.3.6
├─ react-native-svg@6.3.1
├─ react-native-tab-view@0.0.74
├─ react-native-video@2.2.0
├─ react-native@0.53.3
├─ react-proxy@1.1.8
├─ react-redux@5.0.6
├─ react-timer-mixin@0.13.3
├─ react-transform-hmr@1.0.4
├─ react@16.2.0
├─ read-env@1.2.0
├─ read-pkg-up@2.0.0
├─ read-pkg@2.0.0
├─ readable-stream@2.3.6
├─ redux-persist-transform-immutable@4.3.0
├─ redux-persist@5.5.0
├─ redux@3.7.2
├─ regenerate@1.4.0
├─ regenerator-runtime@0.11.1
├─ regenerator-transform@0.10.1
├─ regex-cache@0.4.4
├─ regex-not@1.0.2
├─ regexpu-core@2.0.0
├─ regjsgen@0.2.0
├─ regjsparser@0.1.5
├─ remove-trailing-separator@1.1.0
├─ repeat-element@1.1.2
├─ repeat-string@1.6.1
├─ repeating@2.0.1
├─ request@2.87.0
├─ require-directory@2.1.1
├─ require-main-filename@1.0.1
├─ requires-port@1.0.0
├─ resolve-url@0.2.1
├─ response-time@2.3.2
├─ restore-cursor@2.0.0
├─ ret@0.1.15
├─ reusify@1.0.4
├─ rimraf@2.6.2
├─ rndm@1.2.0
├─ route-parser@0.0.5
├─ rsvp@3.6.2
├─ run-async@2.3.0
├─ rx-lite-aggregates@4.0.8
├─ rx-lite@4.0.8
├─ rx@4.1.0
├─ rxjs@5.5.11
├─ safe-buffer@5.1.2
├─ safe-regex@1.1.0
├─ safer-buffer@2.1.2
├─ sane@2.5.2
├─ sax@1.1.6
├─ semver@5.4.1
├─ send@0.13.2
├─ serialize-error@2.1.0
├─ serve-favicon@2.3.2
├─ serve-index@1.7.3
├─ serve-static@1.10.3
├─ set-blocking@2.0.0
├─ set-value@2.0.0
├─ setimmediate@1.0.5
├─ shebang-command@1.2.0
├─ shebang-regex@1.0.0
├─ shell-quote@1.6.1
├─ shellwords@0.1.1
├─ signal-exit@3.0.2
├─ simple-plist@0.2.1
├─ simple-swizzle@0.2.2
├─ slash@1.0.0
├─ slide@1.1.6
├─ snapdragon-node@2.1.1
├─ snapdragon-util@3.0.1
├─ snapdragon@0.8.2
├─ source-map-resolve@0.5.2
├─ source-map-support@0.4.18
├─ source-map-url@0.4.0
├─ source-map@0.5.7
├─ spdx-correct@3.0.0
├─ spdx-exceptions@2.1.0
├─ spdx-expression-parse@3.0.0
├─ spdx-license-ids@3.0.0
├─ split-string@3.1.0
├─ sshpk@1.14.2
├─ stacktrace-parser@0.1.4
├─ static-extend@0.1.2
├─ statuses@1.5.0
├─ stream-buffers@2.2.0
├─ stream-counter@0.2.0
├─ strict-uri-encode@1.1.0
├─ string_decoder@1.1.1
├─ string-width@2.1.1
├─ strip-ansi@3.0.1
├─ strip-bom@3.0.0
├─ strip-eof@1.0.0
├─ strip-json-comments@2.0.1
├─ supports-color@2.0.0
├─ symbol-observable@1.2.0
├─ tar@4.4.4
├─ temp@0.8.3
├─ throat@4.1.0
├─ through@2.3.8
├─ through2@2.0.3
├─ time-stamp@1.1.0
├─ timed-out@4.0.1
├─ tmp@0.0.33
├─ tmpl@1.0.4
├─ to-fast-properties@1.0.3
├─ to-object-path@0.3.0
├─ to-regex-range@2.1.1
├─ to-regex@3.0.2
├─ tough-cookie@2.3.4
├─ transit-immutable-js@0.7.0
├─ transit-js@0.8.861
├─ trim-right@1.0.1
├─ tsscmp@1.0.5
├─ tunnel-agent@0.6.0
├─ tweetnacl@0.14.5
├─ type-is@1.6.16
├─ typedarray-to-buffer@3.1.5
├─ typedarray@0.0.6
├─ ua-parser-js@0.7.18
├─ uglify-es@3.3.9
├─ uid-safe@2.0.0
├─ ultron@1.0.2
├─ union-value@1.0.0
├─ unpipe@1.0.0
├─ unset-value@1.0.0
├─ urix@0.1.0
├─ url-parse-lax@1.0.0
├─ url-parse@1.2.0
├─ url-to-options@1.0.1
├─ use@3.1.0
├─ utf8@2.1.2
├─ util-deprecate@1.0.2
├─ utils-merge@1.0.0
├─ uuid@3.0.1
├─ validate-npm-package-license@3.0.3
├─ validator@9.1.1
├─ vary@1.0.1
├─ verror@1.10.0
├─ vhost@3.0.2
├─ walker@1.0.7
├─ watch@0.18.0
├─ whatwg-fetch@1.1.1
├─ which-module@2.0.0
├─ which@1.3.1
├─ wide-align@1.1.3
├─ win-release@1.1.1
├─ wordwrap@1.0.0
├─ wrap-ansi@2.1.0
├─ wrappy@1.0.2
├─ write-file-atomic@1.3.4
├─ ws@1.1.5
├─ xcode@0.9.3
├─ xmlbuilder@8.2.2
├─ xmldoc@0.4.0
├─ xmldom@0.1.27
├─ xpipe@1.0.5
├─ xtend@4.0.1
├─ y18n@3.2.1
├─ yallist@3.0.2
├─ yargs-parser@7.0.0
└─ yargs@9.0.1
```

Config:

```
  Sentry.config(DSN, {
    debug: isDev,
    release: packageJSON.version,
  }).install();
```

---
I have following issue:

When I turn on `Debug JS Remotely`, app crashes with error message below.

```
07-05 13:39:13.759 7347-7615/com.noahclient.dev E/unknown:ReactNative: Exception in native call
    com.facebook.react.bridge.NoSuchKeyException: couldn't find key stacktrace in dynamic object
        at com.facebook.react.bridge.ReadableNativeMap.getMap(Native Method)
        at io.sentry.RNSentryModule.captureEvent(RNSentryModule.java:265)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
        at java.lang.Thread.run(Thread.java:764)
```

**Steps to reproduce:**
- Step
 - Run application
 - Turn on `Debug JS Remotely`

**Actual result:**
- Actual: App runs normally

**Expected result:**
- Result: App crashes with the error message above

**Comment by kyo504** [comment]
We have moved to another service so I close this.

**Comment by klapperkopp** [comment]
I am having the same problem. Could you reopen?

**Comment by HazAT** [comment]
How do I reproduce this, does this only happen when remote debugging on Android?

**Comment by st-sloth** [comment]
I too have what seems to be this error on react-native-sentry@0.38.3
![screenshot_1533485768](https://user-images.githubusercontent.com/19147756/43687840-3fe3e9ce-98f6-11e8-83ff-1bd0601a557e.jpg)

Yes, this error only happens when remote debugging on Android and when an error is being captured.

**Comment by mahmoudfelfel** [comment]
It happens only when the remote debugger is on. had to disable sentry on android while debugging, just comment the `Sentry.config('<url>').install();` line, not sure if there is a better way to disable it though.

**Comment by numen31337** [comment]
Same issue here `react-native-sentry@0.38.3`, `react-native@0.56.0`.

**Comment by kevinNejad** [comment]
It happends when your app crashes and your remote debugger is running.
I comment out Sentry while I'm debugging.

**Comment by luco** [comment]
Any updates on this?

**Comment by apski** [comment]
Also having this problem...

**Comment by lukecyca** [comment]
We're also having this problem. For now we disable Sentry while using remote debugging.

**Comment by equesteo** [comment]
I am experiencing this error in production with no remote debugging set up. It is intermittent and rare, but happens:

```
com.facebook.react.bridge.NoSuchKeyException: couldn't find key stacktrace in dynamic object
    at com.facebook.react.bridge.ReadableNativeMap.getMapNative(ReadableNativeMap.java)
    at com.facebook.react.bridge.ReadableNativeMap.getMap(ReadableNativeMap.java:186)
    at io.sentry.RNSentryModule.captureEvent(RNSentryModule.java:265)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
    at android.os.Looper.loop(Looper.java:193)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
    at java.lang.Thread.run(Thread.java:764)
```

**Comment by CristianOspina** [comment]
Hello, any news on this? Same thing happening here 😢

**Comment by equesteo** [comment]
I eventually found the cause of this error for my particular case. I was directly `throw`ing the error object PouchDB gave back. I solved it by converting the PouchDB error object to a native error. I would expect the SDK to handle this case, but apparently you have to be very careful what kind of errors you're throwing.

**Comment by gwmccull** [comment]
I had the same issue.  Once I turned off the `Sentry.config` line, I saw that I had a promise with an unhandled rejection.  Adding a `.catch(() => null)` to that promise (to swallow the error) fixed the native crash

That said, I would expect the Sentry SDK to be able to deal with unhandled promise rejections

**Comment by AChevallier** [comment]
I have the same issue...
Could be nice to have a real fix :)
This issue has been open  for too long 😢

**Comment by AlexeyVlasenko** [comment]
I have same issue.

**Comment by NelGarbuzova** [comment]
It seems, that Sentry cannot catch some error and crashes the app. **gwmccull** 's solution to figure out the error works. But it is temp solution, need fix in Sentry project code.

**Comment by petergaultney** [comment]
I'm experiencing this as well. 
![sentry_capture_event_rsod](https://user-images.githubusercontent.com/549720/55194551-0dbe2000-5178-11e9-9ad5-a5917fa3844a.png)

**Comment by gamsim** [comment]
I solved this by setting Sentry config handlePromiseRejection to false in debug mode

Sentry.config(Config.SENTRY_KEY, {
  handlePromiseRejection: !__DEV__
}).install();

**Comment by petergaultney** [comment]
Our issue is also being caused by an unhandled promise rejection. With Sentry disabled I get a warning in the console, unfortunately without a stacktrace, which means I've not been able to find the specific offender and attach a catch to it (assuming it's even in our code and not in a library somewhere).

Our programmatic workaround is also to disable Sentry while remote debugging. Concretely, we're defining `const haveRemoteDev = typeof DedicatedWorkerGlobalScope !== 'undefined'`  and then only calling `Sentry.config` and the rest of our setup if that boolean is false.

It's unfortunate not to have Sentry working in our local dev environments, as sometimes the output can actually be better than the remote debugger. But it's obviously not worth the occasional crashes.

Sentry devs, if anyone is listening, it would be really nice to have an actual fix for this issue. It's clearly bad behavior to be crashing the app in your code.

**Comment by t0m0120** [comment]
I have the same issue while remote debugging.
I feel that this error is displayed when there is a `Possible Unhandled Promise Rejection`.

**Comment by KoenvGinkel** [comment]
Same^

**Comment by jdegger** [comment]
We solved this problem by disabling native integration on android in dev mode:

```javascript
Sentry.config(Constants.XG_SENTRY_KEY, {
  deactivateStacktraceMerging: true,
  disableNativeIntegration: __DEV__ === true && Platform.OS === 'android',
}).install();
```

The impact of this is minimal and it solves the problem. The inspiration for this solution came from https://github.com/getsentry/react-native-sentry/issues/6

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
