### ISSUE TITLE
Quota exceeded returns error 429 and causes RN Android App crash

### ISSUE THREAD

**Issue by ashugit** [getsentry/sentry-react-native#581]
_Platform:_
- [ ]  iOS
- [x]  Android

Node v11.0.0
npm 6.4.1
react-native-sentry@0.42.0

Config:

```
Sentry.config('https://Key@sentry.io/code',
        {
          logLevel: SentryLog.Debug,
          deactivateStacktraceMerging: false
        }).install();
```

---
I have following issue:
Android ReactNative App Crashes after the quota is exceeded for our paid Sentry subscription.
We get a crash log post the following Raven error
ReactNativeJS: 'Raven transport failed to send: ', { [Error: Sentry error code: 429]

at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:122)
        at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:126)
        at com.facebook.react.bridge.ReadableNativeMap.getInt(ReadableNativeMap.java:180)
        at com.facebook.react.util.JSStackTrace.format(JSStackTrace.java:28)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportSoftException(ExceptionsManagerModule.java:46)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:193)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:764)

**Steps to reproduce:**
-Exceed quota and try to captureException

**Actual result:**
- Android App crash

**Expected result:**
- Sentry errors must never be captured by Sentry and crashes should never occur due to Sentry.

**Comment by HazAT** [comment]
I am closing all old issues, please if this is still a problem feel free to revive it.
Also, consider moving to our new SDK `@sentry/react-native` if it still happens there please open a new issue.
