### ISSUE TITLE
npm install failed with Windows

### ISSUE THREAD

**Issue by ccksfh** [getsentry/sentry-react-native#596]
OS:
- [x]  Windows
- [ ]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.12.0
6.4.1
EcrmApp@0.0.1 Q:\EcrmApp
+-- @sensors.data/react-native-sensors-analytics@1.0.0
+-- axios@0.18.0
+-- husky@1.3.1
+-- jsc-android@236355.1.1
+-- mobx@4.8.0
+-- mobx-react@5.4.3
+-- react@16.6.3
+-- react-native@0.58.6
+-- react-native-config@0.11.7
+-- react-native-gesture-handler@1.1.0
+-- react-native-splash-screen@3.2.0
+-- react-native-webview@5.8.1
`-- react-navigation@3.5.1

```

---
I have following issue:

Description goes here 
```
1245 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
1245 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
1245 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
1245 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
1246 verbose stack Error: @sentry/cli@1.44.3 install: `node scripts/install.js`
1246 verbose stack Exit status 1
1246 verbose stack     at EventEmitter.<anonymous> (C:\Users\ck\AppData\Roaming\nvm\v8.12.0\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
1246 verbose stack     at emitTwo (events.js:126:13)
1246 verbose stack     at EventEmitter.emit (events.js:214:7)
1246 verbose stack     at ChildProcess.<anonymous> (C:\Users\ck\AppData\Roaming\nvm\v8.12.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
1246 verbose stack     at emitTwo (events.js:126:13)
1246 verbose stack     at ChildProcess.emit (events.js:214:7)
1246 verbose stack     at maybeClose (internal/child_process.js:915:16)
1246 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
1247 verbose pkgid @sentry/cli@1.44.3
1248 verbose cwd Q:\EcrmApp
1249 verbose Windows_NT 10.0.17134
1250 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "react-native-sentry"
1251 verbose node v8.12.0
1252 verbose npm  v6.4.1
1253 error code ELIFECYCLE
1254 error errno 1
1255 error @sentry/cli@1.44.3 install: `node scripts/install.js`
1255 error Exit status 1
1256 error Failed at the @sentry/cli@1.44.3 install script.
1256 error This is probably not a problem with npm. There is likely additional logging output above.
1257 verbose exit [ 1, true ]
```

**Steps to reproduce:**
- npm install react-native-sentry --save
- I've tried @0.42.0 & lastest, all failed
- MacOS is ok

**Actual result:**
- failed

**Expected result:**
- success

**Comment by JongtaekChoi** [comment]
I have the same issue at macOS

**Comment by ccksfh** [comment]
> I had the same issue at macOS.
> I recommend trying to run 'node node_modules/@sentry/cli/scripts/install.js' and check the error.
> In my case, the error message is 'Error: EACCES: permission denied, open '/Users/aitrics/.npm/sentry-cli/b5de9c-sentry-cli-Darwin-x86-64.14321-f9be98acde1ad.tmp'.

FYI ,I've solved this by `npm install --sentrycli_cdnurl=https://npm.taobao.org/mirrors/sentry-cli/`
