### ISSUE TITLE
IllegalArgumentException - com.segment.analytics.reactnative.core.RNAnalyticsModule in identify at line 2

### ISSUE THREAD

**Issue by dgobaud** [getsentry/sentry-react-native#654]
- [x]  Android

SDK:
- [x]  `react-native-sentry` 0.43.2

`react-native` version: 059.10

---
```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter userId
    at com.segment.analytics.reactnative.core.RNAnalyticsModule.identify
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
    at android.os.Looper.loop(Looper.java:214)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
    at java.lang.Thread.run(Thread.java:764)
```

**Comment by HazAT** [comment]
Can you provide a repro case for that? It doesn't seem like to be related to the Sentry SDK.

**Comment by dgobaud** [comment]
so the problem is in identify seems like we were passing null but still it shouldn't crash would be better return false...

**Comment by HazAT** [comment]
@dgobaud Where are you passing `null`?
I need a bit more context if I should help you.

**Comment by dgobaud** [comment]
```ts
import analytics from '@segment/analytics-react-native';
analytics.identify(null, { email });
```

**Comment by HazAT** [comment]
Thanks, can you explain where the bug in our SDK should be?
I need to be able to reproduce this crash in order to fix the bug in our SDK.
As it seems to me right now is that `@segment/analytics-react-native` is crashing and not our SDK.

**Comment by dgobaud** [comment]
lol yes sorry! i use you both....... got to the wrong repo.... posted in the right place now.... https://github.com/segmentio/analytics-react-native/issues/107
