### ISSUE TITLE
Android bulid - Task :@sentry-react-native:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by felixchan** [getsentry/sentry-react-native#707]
_Platform:_
- [ ]  iOS
- [X ]  Android

SDK:
- [X ]  `@sentry/react-native` ("@sentry/react-native": "^1.0.4")
- [ ]  `react-native-sentry`

`react-native` version: 0.61.1

## Error Message:

```
> Task :@sentry-react-native:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings
30 actionable tasks: 1 executed, 29 up-to-date
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
/Users/fchan/Developer/myApp/aether/node_modules/@sentry/react-native/android/src/main/java/io/sentry/RNSentryModule.java:190: error: incompatible types: String cannot be converted to Type
                    breadcrumbBuilder.setType(breadcrumb.getString("type"));
                                                                  ^
Note: /Users/fchan/Developer/myApp/aether/node_modules/@sentry/react-native/android/src/main/java/io/sentry/RNSentryModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
1 error
3 warnings

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':@sentry-react-native:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
/Users/fchan/Developer/myApp/aether/node_modules/@sentry/react-native/android/src/main/java/io/sentry/RNSentryModule.java:190: error: incompatible types: String cannot be converted to Type
                    breadcrumbBuilder.setType(breadcrumb.getString("type"));
                                                                  ^
Note: /Users/fchan/Developer/myApp/aether/node_modules/@sentry/react-native/android/src/main/java/io/sentry/RNSentryModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
1 error
3 warnings

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':@sentry-react-native:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s

    at checkExecSyncError (child_process.js:637:11)
    at execFileSync (child_process.js:655:13)
    at runOnAllDevices (/Users/fchan/Developer/myApp/aether/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:74:39)
    at buildAndRun (/Users/fchan/Developer/myApp/aether/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:158:41)
    at then.result (/Users/fchan/Developer/myApp/aether/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)

```

In build.gradle:

```
apply from: "../../node_modules/@sentry/react-native/sentry.gradle"
dependencies {
    implementation project(':@sentry-react-native') //note: hyphen, not underscore
...
```

In settings.gradle:
```
include ':@sentry-react-native' //note: hyphen, not underscore
project(':@sentry-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/@sentry/react-native/android')
```

In MainApplication.java:

```
		@Override
		protected List<ReactPackage> getPackages() {
			@SuppressWarnings("UnnecessaryLocalVariable")
			List<ReactPackage> packages = new PackageList(this).getPackages();
			packages.add(new RNSentryPackage())
			return packages;
		}
```

**Comment by felixchan** [comment]
Why does running the link wizard append lines that have underscore, not hyphen? `include ':@sentry_react-native'` but the docs have hyphen?

**Comment by felixchan** [comment]
Closed. Upgraded to 1.0.9 :)

**Comment by beshur** [comment]
Solved for me running `build` in Arduino Studio, and only then running 'run' command.
