### ISSUE TITLE
error: bundling failed: Error: Unable to resolve module `./tracing` 

### ISSUE THREAD

**Issue by superphil0** [getsentry/sentry-react-native#737]
OS:
- [x]  Windows
- [ ]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.61.4
    "@sentry/react-native": "^1.2.1",

Init Code:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue:

Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `./tracing` from `node_modules\@sentry\integrations\dist\index.js`:

None of these files exist:
  * node_modules\@sentry\integrations\dist\tracing(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules\@sentry\integrations\dist\tracing\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (C:\code\pocketcoach-app\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (C:\code\pocketcoach-app\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (C:\code\pocketcoach-app\node_modules\metro\src\node-haste\DependencyGraph.js:282:16)
    at Object.resolve (C:\code\pocketcoach-app\node_modules\metro\src\lib\transformHelpers.js:267:42)
    at dependencies.map.result (C:\code\pocketcoach-app\node_modules\metro\src\DeltaBundler\traverseDependencies.js:426:31)
    at Array.map (<anonymous>)
    at resolveDependencies (C:\code\pocketcoach-app\node_modules\metro\src\DeltaBundler\traverseDependencies.js:423:18)
    at C:\code\pocketcoach-app\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\code\pocketcoach-app\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)
 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓░░░░░░░░░░ 41.0% (953/1488), failed.

**Steps to reproduce:**
sentry-wizard -i reactNative -p ios android --skip-connect

- npm run android

weird thing is, if I go to node_modules\@sentry\integrations\dist\index.js`
it does nowhere require tracing, i am coming from sentry-expo and rn < 0.60 can this be cached somewhere?

**Actual result:**
- does not build

**Expected result:**
- does build

**Comment by superphil0** [comment]
ok react-native start "--reset-cache"
did the trick -.-
