### ISSUE TITLE
Crashes on build: Could not find io.sentry:sentry-android:2.0.0-rc04

### ISSUE THREAD

**Issue by AdamGerthel** [getsentry/sentry-react-native#768]
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

Platform:
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.1
`react-native` version: 0.61.4

---
I have following issue:

Getting a following fatal error when building. AFAIK this did not happen just yesterday, but I just recently ejected from Expo so all of these non-Expo RN things are brand new to me. I've tried re-linking to no avail.
````
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:preDebugBuild'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find io.sentry:sentry-android:2.0.0-rc04.
     Searched in the following locations:
       - file:/Users/insats/Library/Android/sdk/extras/m2repository/io/sentry/sentry-android/2.0.0-rc04/sentry-android-2.0.0-rc04.pom
       - file:/Users/insats/Library/Android/sdk/extras/m2repository/io/sentry/sentry-android/2.0.0-rc04/sentry-android-2.0.0-rc04.jar
       - file:/Users/insats/Library/Android/sdk/extras/google/m2repository/io/sentry/sentry-android/2.0.0-rc04/sentry-android-2.0.0-rc04.pom
       - file:/Users/insats/Library/Android/sdk/extras/google/m2repository/io/sentry/sentry-android/2.0.0-rc04/sentry-android-2.0.0-rc04.jar
       - file:/Users/insats/Library/Android/sdk/extras/android/m2repository/io/sentry/sentry-android/2.0.0-rc04/sentry-android-2.0.0-rc04.pom
       - file:/Users/insats/Library/Android/sdk/extras/android/m2repository/io/sentry/sentry-android/2.0.0-rc04/sentry-android-2.0.0-rc04.jar
       - file:/Users/insats/.m2/repository/io/sentry/sentry-android/2.0.0-rc04/sentry-android-2.0.0-rc04.pom
       - file:/Users/insats/.m2/repository/io/sentry/sentry-android/2.0.0-rc04/sentry-android-2.0.0-rc04.jar
       - https://dl.google.com/dl/android/maven2/io/sentry/sentry-android/2.0.0-rc04/sentry-android-2.0.0-rc04.pom
       - https://dl.google.com/dl/android/maven2/io/sentry/sentry-android/2.0.0-rc04/sentry-android-2.0.0-rc04.jar
       - https://jcenter.bintray.com/io/sentry/sentry-android/2.0.0-rc04/sentry-android-2.0.0-rc04.pom
       - https://jcenter.bintray.com/io/sentry/sentry-android/2.0.0-rc04/sentry-android-2.0.0-rc04.jar
       - file:/Users/insats/Sites/cyoa-native/node_modules/react-native/android/io/sentry/sentry-android/2.0.0-rc04/sentry-android-2.0.0-rc04.pom
       - file:/Users/insats/Sites/cyoa-native/node_modules/react-native/android/io/sentry/sentry-android/2.0.0-rc04/sentry-android-2.0.0-rc04.jar
       - file:/Users/insats/Sites/cyoa-native/node_modules/jsc-android/dist/io/sentry/sentry-android/2.0.0-rc04/sentry-android-2.0.0-rc04.pom
       - file:/Users/insats/Sites/cyoa-native/node_modules/jsc-android/dist/io/sentry/sentry-android/2.0.0-rc04/sentry-android-2.0.0-rc04.jar
     Required by:
         project :app > project :@sentry_react-native

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

    at checkExecSyncError (child_process.js:616:11)
    at execFileSync (child_process.js:634:13)
    at runOnAllDevices (/Users/insats/Sites/cyoa-native/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:94:39)
    at buildAndRun (/Users/insats/Sites/cyoa-native/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:179:41)
    at then.result (/Users/insats/Sites/cyoa-native/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:133:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by marandaneto** [comment]
hey, we already have an issue for that, please look at #767 there's a workaround over there, thanks.
