### ISSUE TITLE
Unhandled exception in FileObserver io.sentry.android.core.EnvelopeFileObserver

### ISSUE THREAD

**Issue by listenzz** [getsentry/sentry-react-native#775]
OS:
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

Platform:
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.1
`react-native` version: 0.61.5

Init Code:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
I have following issue:

```
2020-02-21 11:44:40.257 14889-14949/com.shundaojia.myapp E/FileObserver: Unhandled exception in FileObserver io.sentry.android.core.EnvelopeFileObserver@7b5ba1d
    java.lang.IllegalArgumentException: Invalid envelope. Item at index '1'. has no header delimiter.
        at io.sentry.core.EnvelopeReader.read(EnvelopeReader.java:30)
        at io.sentry.core.EnvelopeSender.processFile(EnvelopeSender.java:3)
        at io.sentry.core.EnvelopeSender.processEnvelopeFile(EnvelopeSender.java:1)
        at io.sentry.android.core.EnvelopeFileObserver.onEvent(EnvelopeFileObserver.java:4)
        at android.os.FileObserver$ObserverThread.onEvent(FileObserver.java:163)
        at android.os.FileObserver$ObserverThread.observe(Native Method)
        at android.os.FileObserver$ObserverThread.run(FileObserver.java:113)
```

**Steps to reproduce:**

Call method:
```js
 reject = () => {
    Promise.reject(new Error('Something Wrong!'))
  }

  throw = () => {
    throw new Error('Throw something')
  }
```

**Comment by listenzz** [comment]
https://github.com/getsentry/sentry-android/issues/273
