### ISSUE TITLE
Android production build crashes `p.createElement is undefined`

### ISSUE THREAD

**Issue by thomas-coinjar** [getsentry/sentry-react-native#801]
OS:
- [ ]  Windows
- [ ]  MacOS
- [x]  Linux

Platform:
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.1
`react-native` version: 0.61.5

Are you using Expo?
- [ ]  Yes
- [x]  Hell no

Are you using sentry.io or on-premise?
- [x]  sentry.io (SaaS)
- [ ]  on-premise

Configuration:

```
Sentry.init({
    dsn: 'https://<hash>@sentry.io/<cust-no>',
    beforeBreadcrumb(sentryEvent) {
      sentryEvent.data.sessionToken = <session token>;
      return sentryEvent;
    }
  });
Sentry.setTags({
    environment: 'production',
    react: true
  });
```

---
I have following issue:
Android `debug` build runs find but once we run the `production build` the app crashes at startup.

The logcat output suggests that `createElement is not a function`

```
03-18 22:15:47.681  7093  7134 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
03-18 22:15:47.681  7093  7134 E AndroidRuntime: Process: com.our.app, PID: 7093
03-18 22:15:47.681  7093  7134 E AndroidRuntime: com.facebook.react.common.JavascriptException: TypeError: p.createElement is not a function. (In 'p.createElement('iframe')', 'p.createElement' is undefined), stack:
03-18 22:15:47.681  7093  7134 E AndroidRuntime: supportsNativeFetch@1098:749
03-18 22:15:47.681  7093  7134 E AndroidRuntime: v@1099:1077
03-18 22:15:47.681  7093  7134 E AndroidRuntime: p@1099:296
03-18 22:15:47.681  7093  7134 E AndroidRuntime: addInstrumentationHandler@1099:4355
03-18 22:15:47.681  7093  7134 E AndroidRuntime: setupOnce@1128:2799
03-18 22:15:47.681  7093  7134 E AndroidRuntime: s@1104:734
03-18 22:15:47.681  7093  7134 E AndroidRuntime: <unknown>@1104:1024
03-18 22:15:47.681  7093  7134 E AndroidRuntime: forEach@-1
03-18 22:15:47.681  7093  7134 E AndroidRuntime: setupIntegrations@1104:998
03-18 22:15:47.681  7093  7134 E AndroidRuntime: s@1103:317
03-18 22:15:47.681  7093  7134 E AndroidRuntime: p@1134:356
03-18 22:15:47.681  7093  7134 E AndroidRuntime: initAndBind@1107:196
03-18 22:15:47.681  7093  7134 E AndroidRuntime: init@1136:996
03-18 22:15:47.681  7093  7134 E AndroidRuntime: setupSentry@3090:821
03-18 22:15:47.681  7093  7134 E AndroidRuntime: <unknown>@8:252
03-18 22:15:47.681  7093  7134 E AndroidRuntime: v@2:1474
03-18 22:15:47.681  7093  7134 E AndroidRuntime: <unknown>@6:38
03-18 22:15:47.681  7093  7134 E AndroidRuntime: v@2:1474
03-18 22:15:47.681  7093  7134 E AndroidRuntime: d@2:876
03-18 22:15:47.681  7093  7134 E AndroidRuntime: global code@3093:4
03-18 22:15:47.681  7093  7134 E AndroidRuntime: 
03-18 22:15:47.681  7093  7134 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:71)
03-18 22:15:47.681  7093  7134 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-18 22:15:47.681  7093  7134 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
03-18 22:15:47.681  7093  7134 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
03-18 22:15:47.681  7093  7134 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
03-18 22:15:47.681  7093  7134 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
03-18 22:15:47.681  7093  7134 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
03-18 22:15:47.681  7093  7134 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
03-18 22:15:47.681  7093  7134 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
03-18 22:15:47.681  7093  7134 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
03-18 22:15:47.681  7093  7134 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
```

**Steps to reproduce:**
- Bundle JS of a RN app
```
react-native bundle --entry-file index.js \
      --platform android \
      --dev false \
      --bundle-output android/app/src/main/assets/index.android.bundle \
      --sourcemap-output ./sentry/android.main.bundle.map \
      --assets-dest android/app/src/main/res
```
- Compile APK
`./gradlew app:assembleRelease -x bundleReleaseJsAndAssets`

**Actual result:**
- Production build crashes at startup 

I logged out what `global` actually is within our app. Here the truncated output:
`node_modules/@sentry/utils/dist/supports.js` line 107

```
{
  "process": {
    "env": {
      "NODE_ENV": "production"
    }
  },
  "__DEV__": false,
  "__BUNDLE_START_TIME__": 1584572364916,
  "__jsiExecutorDescription": "<JSCRuntime@0x893c80c0>",
  "nativeModuleProxy": {},
  "ErrorUtils": {},
  "GLOBAL": "__cycle__",
  "window": "__cycle__",
  "self": "__cycle__",
  "navigator": {
    "product": "ReactNative"
  },
  "regeneratorRuntime": {},
  ...
  "__SENTRY__": {
    "logger": {
      "_enabled": false
    },
    "hub": {
      "_version": 3,
      "_stack": [
        {
          "scope": {
            "_notifyingListeners": false,
            "_scopeListeners": [],
            "_eventProcessors": [],
            "_breadcrumbs": [],
            "_user": {},
            "_tags": {},
            "_extra": {},
            "_context": {}
          }
        }
      ]
    },
    "globalEventProcessors": [
      null,
      null,
      null,
      null
    ]
  },
  "document": {}
}
```

It clearly shows that `document` is an empty object and therefore has no function `createElement`. I'm not sure why that is.

If I change the source code of `node_modules/@sentry/utils/dist/supports.js` (line 109) like that

```
if (doc && doc.createElement === 'function') {
  var sandbox = doc.createElement('iframe');
  ...
}
```

the app runs fine

**Expected result:**
- Production build should not crash at startup

**Comment by thomas-coinjar** [comment]
@HazAT do you have an idea? It seems it's related to this change https://github.com/getsentry/sentry-react-native/blame/83600874562a91f11f69ff0abe1b71c7f4a63841/src/js/sdk.ts#L43

**Comment by marandaneto** [comment]
are still having the same issue using the latest Sentry RN SDK Version? I can't reproduce it
